//////////////////////////////////////////
// Generated by XmlMsgGen.  Do not edit //
//////////////////////////////////////////

#pragma once

interface IXmlPacket;
class CItemStoreDiff;
namespace Gun2
{

///////////////////////////////////////

class CConnectResult: public CBaseResult
{
public:
    CConnectResult( IXmlPacket* pXmlPkt );
    CConnectResult( void );
    ~CConnectResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, DWORD Random, LPBLOB Key );

    inline STDMETHODIMP
    CConnectResult::GetRandom( OUT DWORD* pRandom )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pRandom = m_Random;
        return S_OK;
    }

    inline STDMETHODIMP
    CConnectResult::GetKey( OUT LPBLOB* pKey )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pKey = m_Key;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_Random;
    LPBLOB m_Key;
};

///////////////////////////////////////

class CConnectInfoResult: public CBaseResult
{
public:
    CConnectInfoResult( IXmlPacket* pXmlPkt );
    CConnectInfoResult( void );
    ~CConnectInfoResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, DWORD Time );

    inline STDMETHODIMP
    CConnectInfoResult::GetTime( OUT DWORD* pTime )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pTime = m_Time;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_Time;
};

///////////////////////////////////////

class CConnectEvent: public CBaseEvent
{
public:
    CConnectEvent( IXmlPacket* pXmlPkt );
    CConnectEvent( void );
    ~CConnectEvent( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( DWORD nada, DWORD Time );

    inline STDMETHODIMP
    CConnectEvent::GetTime( OUT DWORD* pTime )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pTime = m_Time;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_Time;
};

///////////////////////////////////////

class CDisconnectEvent: public CBaseEvent
{
public:
    CDisconnectEvent( IXmlPacket* pXmlPkt );
    CDisconnectEvent( void );
    ~CDisconnectEvent( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( DWORD nada );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CConnectFailedEvent: public CBaseEvent
{
public:
    CConnectFailedEvent( IXmlPacket* pXmlPkt );
    CConnectFailedEvent( void );
    ~CConnectFailedEvent( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( DWORD nada );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CGetNewsResult: public CBaseResult
{
public:
    CGetNewsResult( IXmlPacket* pXmlPkt );
    CGetNewsResult( void );
    ~CGetNewsResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, LPCWSTR News );

    inline STDMETHODIMP
    CGetNewsResult::GetNews( OUT LPCWSTR* pNews )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pNews = m_News;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    LPCWSTR m_News;
};

///////////////////////////////////////

class CLoginResult: public CBaseResult
{
public:
    CLoginResult( IXmlPacket* pXmlPkt );
    CLoginResult( void );
    ~CLoginResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, DWORD Status );

    inline STDMETHODIMP
    CLoginResult::GetStatus( OUT DWORD* pStatus )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pStatus = m_Status;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_Status;
};

///////////////////////////////////////

class CLogoutResult: public CBaseResult
{
public:
    CLogoutResult( IXmlPacket* pXmlPkt );
    CLogoutResult( void );
    ~CLogoutResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CCreateAccountResult: public CBaseResult
{
public:
    CCreateAccountResult( IXmlPacket* pXmlPkt );
    CCreateAccountResult( void );
    ~CCreateAccountResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CChangePasswordResult: public CBaseResult
{
public:
    CChangePasswordResult( IXmlPacket* pXmlPkt );
    CChangePasswordResult( void );
    ~CChangePasswordResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CChangePasswordFromHintResult: public CBaseResult
{
public:
    CChangePasswordFromHintResult( IXmlPacket* pXmlPkt );
    CChangePasswordFromHintResult( void );
    ~CChangePasswordFromHintResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CGetAccountStatusResult: public CBaseResult
{
public:
    CGetAccountStatusResult( IXmlPacket* pXmlPkt );
    CGetAccountStatusResult( void );
    ~CGetAccountStatusResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, DWORD Status );

    inline STDMETHODIMP
    CGetAccountStatusResult::GetStatus( OUT DWORD* pStatus )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pStatus = m_Status;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_Status;
};

///////////////////////////////////////

class CGetPasswordHintResult: public CBaseResult
{
public:
    CGetPasswordHintResult( IXmlPacket* pXmlPkt );
    CGetPasswordHintResult( void );
    ~CGetPasswordHintResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, LPCWSTR Hint );

    inline STDMETHODIMP
    CGetPasswordHintResult::GetHint( OUT LPCWSTR* pHint )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pHint = m_Hint;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    LPCWSTR m_Hint;
};

///////////////////////////////////////

class CLoginDupEvent: public CBaseEvent
{
public:
    CLoginDupEvent( IXmlPacket* pXmlPkt );
    CLoginDupEvent( void );
    ~CLoginDupEvent( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( DWORD nada );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CLogoutEvent: public CBaseEvent
{
public:
    CLogoutEvent( IXmlPacket* pXmlPkt );
    CLogoutEvent( void );
    ~CLogoutEvent( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( DWORD nada, DWORD Reason );

    inline STDMETHODIMP
    CLogoutEvent::GetReason( OUT DWORD* pReason )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pReason = m_Reason;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_Reason;
};

///////////////////////////////////////

class CGetFriendsListResult: public CBaseResult
{
public:
    CGetFriendsListResult( IXmlPacket* pXmlPkt );
    CGetFriendsListResult( void );
    ~CGetFriendsListResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, DWORD Count, UserStatus* AllFriendsStatus );

    inline STDMETHODIMP
    CGetFriendsListResult::GetCount( OUT DWORD* pCount )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pCount = m_Count;
        return S_OK;
    }

    inline STDMETHODIMP
    CGetFriendsListResult::GetAllFriendsStatus( OUT UserStatus** pAllFriendsStatus )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pAllFriendsStatus = m_AllFriendsStatus;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_Count;
    UserStatus* m_AllFriendsStatus;
};

///////////////////////////////////////

class CFriendAddResult: public CBaseResult
{
public:
    CFriendAddResult( IXmlPacket* pXmlPkt );
    CFriendAddResult( void );
    ~CFriendAddResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CFriendDeleteResult: public CBaseResult
{
public:
    CFriendDeleteResult( IXmlPacket* pXmlPkt );
    CFriendDeleteResult( void );
    ~CFriendDeleteResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CGetIgnoredListResult: public CBaseResult
{
public:
    CGetIgnoredListResult( IXmlPacket* pXmlPkt );
    CGetIgnoredListResult( void );
    ~CGetIgnoredListResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, DWORD Count, LPCWSTR* Ignored );

    inline STDMETHODIMP
    CGetIgnoredListResult::GetCount( OUT DWORD* pCount )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pCount = m_Count;
        return S_OK;
    }

    inline STDMETHODIMP
    CGetIgnoredListResult::GetIgnored( OUT LPCWSTR** pIgnored )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pIgnored = m_Ignored;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_Count;
    LPCWSTR* m_Ignored;
};

///////////////////////////////////////

class CIgnoredAddResult: public CBaseResult
{
public:
    CIgnoredAddResult( IXmlPacket* pXmlPkt );
    CIgnoredAddResult( void );
    ~CIgnoredAddResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CIgnoredDeleteResult: public CBaseResult
{
public:
    CIgnoredDeleteResult( IXmlPacket* pXmlPkt );
    CIgnoredDeleteResult( void );
    ~CIgnoredDeleteResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CFlagsResult: public CBaseResult
{
public:
    CFlagsResult( IXmlPacket* pXmlPkt );
    CFlagsResult( void );
    ~CFlagsResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, DWORD WhichFlag, DWORD Flags );

    inline STDMETHODIMP
    CFlagsResult::GetWhichFlag( OUT DWORD* pWhichFlag )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pWhichFlag = m_WhichFlag;
        return S_OK;
    }

    inline STDMETHODIMP
    CFlagsResult::GetFlags( OUT DWORD* pFlags )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pFlags = m_Flags;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_WhichFlag;
    DWORD m_Flags;
};

///////////////////////////////////////

class CWhereIsResult: public CBaseResult
{
public:
    CWhereIsResult( IXmlPacket* pXmlPkt );
    CWhereIsResult( void );
    ~CWhereIsResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, LPCWSTR UserName, DWORD Mode, LPCWSTR Location );

    inline STDMETHODIMP
    CWhereIsResult::GetUserName( OUT LPCWSTR* pUserName )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pUserName = m_UserName;
        return S_OK;
    }

    inline STDMETHODIMP
    CWhereIsResult::GetMode( OUT DWORD* pMode )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pMode = m_Mode;
        return S_OK;
    }

    inline STDMETHODIMP
    CWhereIsResult::GetLocation( OUT LPCWSTR* pLocation )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pLocation = m_Location;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    LPCWSTR m_UserName;
    DWORD m_Mode;
    LPCWSTR m_Location;
};

///////////////////////////////////////

class CSetLocationResult: public CBaseResult
{
public:
    CSetLocationResult( IXmlPacket* pXmlPkt );
    CSetLocationResult( void );
    ~CSetLocationResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CAcceptAddFriendResult: public CBaseResult
{
public:
    CAcceptAddFriendResult( IXmlPacket* pXmlPkt );
    CAcceptAddFriendResult( void );
    ~CAcceptAddFriendResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CFriendStartEvent: public CBaseEvent
{
public:
    CFriendStartEvent( IXmlPacket* pXmlPkt );
    CFriendStartEvent( void );
    ~CFriendStartEvent( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( DWORD nada, DWORD Count, UserStatus* AllFriendsStatus );

    inline STDMETHODIMP
    CFriendStartEvent::GetCount( OUT DWORD* pCount )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pCount = m_Count;
        return S_OK;
    }

    inline STDMETHODIMP
    CFriendStartEvent::GetAllFriendsStatus( OUT UserStatus** pAllFriendsStatus )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pAllFriendsStatus = m_AllFriendsStatus;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_Count;
    UserStatus* m_AllFriendsStatus;
};

///////////////////////////////////////

class CFriendStatusEvent: public CBaseEvent
{
public:
    CFriendStatusEvent( IXmlPacket* pXmlPkt );
    CFriendStatusEvent( void );
    ~CFriendStatusEvent( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( DWORD nada, LPCWSTR UserName, DWORD Mode );

    inline STDMETHODIMP
    CFriendStatusEvent::GetUserName( OUT LPCWSTR* pUserName )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pUserName = m_UserName;
        return S_OK;
    }

    inline STDMETHODIMP
    CFriendStatusEvent::GetMode( OUT DWORD* pMode )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pMode = m_Mode;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    LPCWSTR m_UserName;
    DWORD m_Mode;
};

///////////////////////////////////////

class CFriendRequestEvent: public CBaseEvent
{
public:
    CFriendRequestEvent( IXmlPacket* pXmlPkt );
    CFriendRequestEvent( void );
    ~CFriendRequestEvent( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( DWORD nada, LPCWSTR UserName );

    inline STDMETHODIMP
    CFriendRequestEvent::GetUserName( OUT LPCWSTR* pUserName )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pUserName = m_UserName;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    LPCWSTR m_UserName;
};

///////////////////////////////////////

class CFriendAddCompleteEvent: public CBaseEvent
{
public:
    CFriendAddCompleteEvent( IXmlPacket* pXmlPkt );
    CFriendAddCompleteEvent( void );
    ~CFriendAddCompleteEvent( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( DWORD nada, DWORD Status, LPCWSTR UserName );

    inline STDMETHODIMP
    CFriendAddCompleteEvent::GetStatus( OUT DWORD* pStatus )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pStatus = m_Status;
        return S_OK;
    }

    inline STDMETHODIMP
    CFriendAddCompleteEvent::GetUserName( OUT LPCWSTR* pUserName )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pUserName = m_UserName;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_Status;
    LPCWSTR m_UserName;
};

///////////////////////////////////////

class CGetListOfRoomsResult: public CBaseResult
{
public:
    CGetListOfRoomsResult( IXmlPacket* pXmlPkt );
    CGetListOfRoomsResult( void );
    ~CGetListOfRoomsResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, DWORD Index, DWORD Total, DWORD Count, ChatRoomAttrs* RoomList );

    inline STDMETHODIMP
    CGetListOfRoomsResult::GetIndex( OUT DWORD* pIndex )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pIndex = m_Index;
        return S_OK;
    }

    inline STDMETHODIMP
    CGetListOfRoomsResult::GetTotal( OUT DWORD* pTotal )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pTotal = m_Total;
        return S_OK;
    }

    inline STDMETHODIMP
    CGetListOfRoomsResult::GetCount( OUT DWORD* pCount )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pCount = m_Count;
        return S_OK;
    }

    inline STDMETHODIMP
    CGetListOfRoomsResult::GetRoomList( OUT ChatRoomAttrs** pRoomList )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pRoomList = m_RoomList;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_Index;
    DWORD m_Total;
    DWORD m_Count;
    ChatRoomAttrs* m_RoomList;
};

///////////////////////////////////////

class CJoinRoomResult: public CBaseResult
{
public:
    CJoinRoomResult( IXmlPacket* pXmlPkt );
    CJoinRoomResult( void );
    ~CJoinRoomResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, DWORD RoomId );

    inline STDMETHODIMP
    CJoinRoomResult::GetRoomId( OUT DWORD* pRoomId )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pRoomId = m_RoomId;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_RoomId;
};

///////////////////////////////////////

class CLeaveRoomResult: public CBaseResult
{
public:
    CLeaveRoomResult( IXmlPacket* pXmlPkt );
    CLeaveRoomResult( void );
    ~CLeaveRoomResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CLeaveAllRoomsResult: public CBaseResult
{
public:
    CLeaveAllRoomsResult( IXmlPacket* pXmlPkt );
    CLeaveAllRoomsResult( void );
    ~CLeaveAllRoomsResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CGetUsersInRoomResult: public CBaseResult
{
public:
    CGetUsersInRoomResult( IXmlPacket* pXmlPkt );
    CGetUsersInRoomResult( void );
    ~CGetUsersInRoomResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, DWORD Count, LPCWSTR* Users );

    inline STDMETHODIMP
    CGetUsersInRoomResult::GetCount( OUT DWORD* pCount )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pCount = m_Count;
        return S_OK;
    }

    inline STDMETHODIMP
    CGetUsersInRoomResult::GetUsers( OUT LPCWSTR** pUsers )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pUsers = m_Users;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_Count;
    LPCWSTR* m_Users;
};

///////////////////////////////////////

class CSendToRoomResult: public CBaseResult
{
public:
    CSendToRoomResult( IXmlPacket* pXmlPkt );
    CSendToRoomResult( void );
    ~CSendToRoomResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CSendToUserResult: public CBaseResult
{
public:
    CSendToUserResult( IXmlPacket* pXmlPkt );
    CSendToUserResult( void );
    ~CSendToUserResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CGetSquelchListResult: public CBaseResult
{
public:
    CGetSquelchListResult( IXmlPacket* pXmlPkt );
    CGetSquelchListResult( void );
    ~CGetSquelchListResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, DWORD Count, LPCWSTR* Ignored );

    inline STDMETHODIMP
    CGetSquelchListResult::GetCount( OUT DWORD* pCount )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pCount = m_Count;
        return S_OK;
    }

    inline STDMETHODIMP
    CGetSquelchListResult::GetIgnored( OUT LPCWSTR** pIgnored )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pIgnored = m_Ignored;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_Count;
    LPCWSTR* m_Ignored;
};

///////////////////////////////////////

class CSquelchAddResult: public CBaseResult
{
public:
    CSquelchAddResult( IXmlPacket* pXmlPkt );
    CSquelchAddResult( void );
    ~CSquelchAddResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CSquelchDeleteResult: public CBaseResult
{
public:
    CSquelchDeleteResult( IXmlPacket* pXmlPkt );
    CSquelchDeleteResult( void );
    ~CSquelchDeleteResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CCreateRoomResult: public CBaseResult
{
public:
    CCreateRoomResult( IXmlPacket* pXmlPkt );
    CCreateRoomResult( void );
    ~CCreateRoomResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, DWORD RoomId );

    inline STDMETHODIMP
    CCreateRoomResult::GetRoomId( OUT DWORD* pRoomId )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pRoomId = m_RoomId;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_RoomId;
};

///////////////////////////////////////

class CGetRoomOwnerResult: public CBaseResult
{
public:
    CGetRoomOwnerResult( IXmlPacket* pXmlPkt );
    CGetRoomOwnerResult( void );
    ~CGetRoomOwnerResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, DWORD RoomId, LPCWSTR UserName );

    inline STDMETHODIMP
    CGetRoomOwnerResult::GetRoomId( OUT DWORD* pRoomId )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pRoomId = m_RoomId;
        return S_OK;
    }

    inline STDMETHODIMP
    CGetRoomOwnerResult::GetUserName( OUT LPCWSTR* pUserName )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pUserName = m_UserName;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_RoomId;
    LPCWSTR m_UserName;
};

///////////////////////////////////////

class CAssignOwnershipResult: public CBaseResult
{
public:
    CAssignOwnershipResult( IXmlPacket* pXmlPkt );
    CAssignOwnershipResult( void );
    ~CAssignOwnershipResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CSetRoomTopicResult: public CBaseResult
{
public:
    CSetRoomTopicResult( IXmlPacket* pXmlPkt );
    CSetRoomTopicResult( void );
    ~CSetRoomTopicResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CSetRoomModeResult: public CBaseResult
{
public:
    CSetRoomModeResult( IXmlPacket* pXmlPkt );
    CSetRoomModeResult( void );
    ~CSetRoomModeResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CInviteUserResult: public CBaseResult
{
public:
    CInviteUserResult( IXmlPacket* pXmlPkt );
    CInviteUserResult( void );
    ~CInviteUserResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CKickOutUserResult: public CBaseResult
{
public:
    CKickOutUserResult( IXmlPacket* pXmlPkt );
    CKickOutUserResult( void );
    ~CKickOutUserResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt );

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
};

///////////////////////////////////////

class CRoomEnterEvent: public CBaseEvent
{
public:
    CRoomEnterEvent( IXmlPacket* pXmlPkt );
    CRoomEnterEvent( void );
    ~CRoomEnterEvent( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( DWORD nada, DWORD RoomId, LPCWSTR UserName );

    inline STDMETHODIMP
    CRoomEnterEvent::GetRoomId( OUT DWORD* pRoomId )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pRoomId = m_RoomId;
        return S_OK;
    }

    inline STDMETHODIMP
    CRoomEnterEvent::GetUserName( OUT LPCWSTR* pUserName )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pUserName = m_UserName;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_RoomId;
    LPCWSTR m_UserName;
};

///////////////////////////////////////

class CRoomLeaveEvent: public CBaseEvent
{
public:
    CRoomLeaveEvent( IXmlPacket* pXmlPkt );
    CRoomLeaveEvent( void );
    ~CRoomLeaveEvent( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( DWORD nada, DWORD RoomId, LPCWSTR UserName );

    inline STDMETHODIMP
    CRoomLeaveEvent::GetRoomId( OUT DWORD* pRoomId )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pRoomId = m_RoomId;
        return S_OK;
    }

    inline STDMETHODIMP
    CRoomLeaveEvent::GetUserName( OUT LPCWSTR* pUserName )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pUserName = m_UserName;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_RoomId;
    LPCWSTR m_UserName;
};

///////////////////////////////////////

class CRoomSpeakEvent: public CBaseEvent
{
public:
    CRoomSpeakEvent( IXmlPacket* pXmlPkt );
    CRoomSpeakEvent( void );
    ~CRoomSpeakEvent( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( DWORD nada, DWORD RoomId, LPCWSTR UserName, LPCWSTR Text );

    inline STDMETHODIMP
    CRoomSpeakEvent::GetRoomId( OUT DWORD* pRoomId )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pRoomId = m_RoomId;
        return S_OK;
    }

    inline STDMETHODIMP
    CRoomSpeakEvent::GetUserName( OUT LPCWSTR* pUserName )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pUserName = m_UserName;
        return S_OK;
    }

    inline STDMETHODIMP
    CRoomSpeakEvent::GetText( OUT LPCWSTR* pText )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pText = m_Text;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_RoomId;
    LPCWSTR m_UserName;
    LPCWSTR m_Text;
};

///////////////////////////////////////

class CUserSpeakEvent: public CBaseEvent
{
public:
    CUserSpeakEvent( IXmlPacket* pXmlPkt );
    CUserSpeakEvent( void );
    ~CUserSpeakEvent( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( DWORD nada, LPCWSTR UserName, LPCWSTR Text );

    inline STDMETHODIMP
    CUserSpeakEvent::GetUserName( OUT LPCWSTR* pUserName )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pUserName = m_UserName;
        return S_OK;
    }

    inline STDMETHODIMP
    CUserSpeakEvent::GetText( OUT LPCWSTR* pText )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pText = m_Text;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    LPCWSTR m_UserName;
    LPCWSTR m_Text;
};

///////////////////////////////////////

class CKickedOutEvent: public CBaseEvent
{
public:
    CKickedOutEvent( IXmlPacket* pXmlPkt );
    CKickedOutEvent( void );
    ~CKickedOutEvent( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( DWORD nada, DWORD RoomId, LPCWSTR Reason );

    inline STDMETHODIMP
    CKickedOutEvent::GetRoomId( OUT DWORD* pRoomId )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pRoomId = m_RoomId;
        return S_OK;
    }

    inline STDMETHODIMP
    CKickedOutEvent::GetReason( OUT LPCWSTR* pReason )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pReason = m_Reason;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_RoomId;
    LPCWSTR m_Reason;
};

///////////////////////////////////////

class CReceiveOwnershipEvent: public CBaseEvent
{
public:
    CReceiveOwnershipEvent( IXmlPacket* pXmlPkt );
    CReceiveOwnershipEvent( void );
    ~CReceiveOwnershipEvent( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( DWORD nada, DWORD RoomId );

    inline STDMETHODIMP
    CReceiveOwnershipEvent::GetRoomId( OUT DWORD* pRoomId )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pRoomId = m_RoomId;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_RoomId;
};

///////////////////////////////////////

class CInvitedEvent: public CBaseEvent
{
public:
    CInvitedEvent( IXmlPacket* pXmlPkt );
    CInvitedEvent( void );
    ~CInvitedEvent( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( DWORD nada, LPCWSTR UserName, LPCWSTR RoomName, LPCWSTR Invitation );

    inline STDMETHODIMP
    CInvitedEvent::GetUserName( OUT LPCWSTR* pUserName )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pUserName = m_UserName;
        return S_OK;
    }

    inline STDMETHODIMP
    CInvitedEvent::GetRoomName( OUT LPCWSTR* pRoomName )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pRoomName = m_RoomName;
        return S_OK;
    }

    inline STDMETHODIMP
    CInvitedEvent::GetInvitation( OUT LPCWSTR* pInvitation )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pInvitation = m_Invitation;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    LPCWSTR m_UserName;
    LPCWSTR m_RoomName;
    LPCWSTR m_Invitation;
};

///////////////////////////////////////

class CGetViewListResult: public CBaseResult
{
public:
    CGetViewListResult( IXmlPacket* pXmlPkt );
    CGetViewListResult( void );
    ~CGetViewListResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, DWORD Count, ViewDescription* ViewList );

    inline STDMETHODIMP
    CGetViewListResult::GetCount( OUT DWORD* pCount )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pCount = m_Count;
        return S_OK;
    }

    inline STDMETHODIMP
    CGetViewListResult::GetViewList( OUT ViewDescription** pViewList )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pViewList = m_ViewList;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_Count;
    ViewDescription* m_ViewList;
};

///////////////////////////////////////

class CGetHeaderRowResult: public CBaseResult
{
public:
    CGetHeaderRowResult( IXmlPacket* pXmlPkt );
    CGetHeaderRowResult( void );
    ~CGetHeaderRowResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, LPGUNROW Headers );

    inline STDMETHODIMP
    CGetHeaderRowResult::GetHeaders( OUT LPGUNROW* pHeaders )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pHeaders = m_Headers;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    LPGUNROW m_Headers;
};

///////////////////////////////////////

class CGetPageResult: public CBaseResult
{
public:
    CGetPageResult( IXmlPacket* pXmlPkt );
    CGetPageResult( void );
    ~CGetPageResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, DWORD Count, LPGUNROW* Rows, DWORD ViewId, DWORD ViewIndex, DWORD ViewTotal );

    inline STDMETHODIMP
    CGetPageResult::GetCount( OUT DWORD* pCount )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pCount = m_Count;
        return S_OK;
    }

    inline STDMETHODIMP
    CGetPageResult::GetRows( OUT LPGUNROW** pRows )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pRows = m_Rows;
        return S_OK;
    }

    inline STDMETHODIMP
    CGetPageResult::GetViewId( OUT DWORD* pViewId )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pViewId = m_ViewId;
        return S_OK;
    }

    inline STDMETHODIMP
    CGetPageResult::GetViewIndex( OUT DWORD* pViewIndex )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pViewIndex = m_ViewIndex;
        return S_OK;
    }

    inline STDMETHODIMP
    CGetPageResult::GetViewTotal( OUT DWORD* pViewTotal )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pViewTotal = m_ViewTotal;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_Count;
    LPGUNROW* m_Rows;
    DWORD m_ViewId;
    DWORD m_ViewIndex;
    DWORD m_ViewTotal;
};

///////////////////////////////////////

class CGetRowPageResult: public CBaseResult
{
public:
    CGetRowPageResult( IXmlPacket* pXmlPkt );
    CGetRowPageResult( void );
    ~CGetRowPageResult( void );
    STDMETHODIMP InitFromPacket( void );
    STDMETHODIMP InitNew( PVOID pvContext, HRESULT hrPkt, DWORD Count, LPGUNROW* Rows, DWORD ViewId, DWORD ViewIndex, DWORD ViewTotal );

    inline STDMETHODIMP
    CGetRowPageResult::GetCount( OUT DWORD* pCount )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pCount = m_Count;
        return S_OK;
    }

    inline STDMETHODIMP
    CGetRowPageResult::GetRows( OUT LPGUNROW** pRows )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pRows = m_Rows;
        return S_OK;
    }

    inline STDMETHODIMP
    CGetRowPageResult::GetViewId( OUT DWORD* pViewId )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pViewId = m_ViewId;
        return S_OK;
    }

    inline STDMETHODIMP
    CGetRowPageResult::GetViewIndex( OUT DWORD* pViewIndex )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pViewIndex = m_ViewIndex;
        return S_OK;
    }

    inline STDMETHODIMP
    CGetRowPageResult::GetViewTotal( OUT DWORD* pViewTotal )
    {
        if( !m_bInited ) return ZT_E_NOT_INITED;
        else
            *pViewTotal = m_ViewTotal;
        return S_OK;
    }

private:
    STDMETHODIMP RenderUnicode(
                    IN LPWSTR pwszDestination,
                    IN DWORD cchSize,
                   OUT DWORD* pcchUsed) const;
private:
    DWORD m_Count;
    LPGUNROW* m_Rows;
    DWORD m_ViewId;
    DWORD m_ViewIndex;
    DWORD m_ViewTotal;
};

};     // Gun2 namespace
