/*++

Copyright (c) 1999-2002  Microsoft Corporation

Module Name:

    GunErr.h

Abstract:

    Definitions for Gun error messages.

Author:


Revision History:

Notes:

    This file is generated by the MC tool from the GunErr.mc file.

--*/

#ifndef _GUNERR_H_
#define _GUNERR_H_


#define STATUS_SEVERITY(hr)  (((hr) >> 30) & 0x3)

// Customer Bit is set by the message compiler command line arguments

/////////////////////////////////////////////////////////////////////////
//
// ZoneTech General Error Codes
//
/////////////////////////////////////////////////////////////////////////

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//
#define FACILITY_ZONETECH                0x112
#define FACILITY_ZNULL                   0x0


//
// Define the severity codes
//
#define STATUS_SEVERITY_WARNING          0x2
#define STATUS_SEVERITY_SUCCESS          0x0
#define STATUS_SEVERITY_INFORMATIONAL    0x1
#define STATUS_SEVERITY_ERROR            0x3


//
// MessageId: ZT_E_VERSION_NOT_AVAIL
//
// MessageText:
//
//  The requested component version in not available.
//
#define ZT_E_VERSION_NOT_AVAIL           0xC1120001L

//
// MessageId: ZT_E_BUFFER_TOO_SMALL
//
// MessageText:
//
//  The provided buffer is too small to complete the operation.
//
#define ZT_E_BUFFER_TOO_SMALL            0xC1120002L

//
// MessageId: ZT_E_INTERNAL
//
// MessageText:
//
//  An internal error occurred.
//
#define ZT_E_INTERNAL                    0xC1120003L

//
// MessageId: ZT_E_INVALID_STATUS
//
// MessageText:
//
//  The ZoneTech object status is not in an expected state.
//
#define ZT_E_INVALID_STATUS              0xC1120004L

//
// MessageId: ZT_E_STR_TOO_LONG
//
// MessageText:
//
//  The string exceeds the maximum supported string length for this operation.
//
#define ZT_E_STR_TOO_LONG                0xC1120005L

//
// MessageId: ZT_E_PENDING
//
// MessageText:
//
//  The operation is pending.
//
#define ZT_E_PENDING                     0xC1120006L

//
// MessageId: ZT_E_ATTR_NOT_FOUND
//
// MessageText:
//
//  The Attribute was not found.
//
#define ZT_E_ATTR_NOT_FOUND              0xC1120007L

//
// MessageId: ZT_E_NOT_INITED
//
// MessageText:
//
//  The Init method for this object must be called before this operation.
//
#define ZT_E_NOT_INITED                  0xC1120008L

//
// MessageId: ZT_E_ALREADY_INITED
//
// MessageText:
//
//  The Init method cannot be called more than once on this object.
//
#define ZT_E_ALREADY_INITED              0xC1120009L

//
// MessageId: ZT_E_WRONG_THREAD
//
// MessageText:
//
//  Call to object was made on the wrong thread.
//
#define ZT_E_WRONG_THREAD                0xC112000AL

//
// MessageId: ZT_E_ASSERT
//
// MessageText:
//
//  %1
//
#define ZT_E_ASSERT                      0xC112000BL

//
// MessageId: ZT_E_INVALID_CHARACTER
//
// MessageText:
//
//  An unconvertible character was found while converting strings.
//
#define ZT_E_INVALID_CHARACTER           0xC112000CL

//
// MessageId: ZT_E_READONLY
//
// MessageText:
//
//  An illegal operation was attempted on a readonly object.
//
#define ZT_E_READONLY                    0xC112000DL

//
// MessageId: ZT_E_MISSING_OBJECT
//
// MessageText:
//
//  An operation failed due a missing object.
//
#define ZT_E_MISSING_OBJECT              0xC112000EL

//
// MessageId: ZT_E_INVALID_OP
//
// MessageText:
//
//  The attempted operation is invalid for this object.
//
#define ZT_E_INVALID_OP                  0xC112000FL

//
// MessageId: ZT_E_TIMEOUT
//
// MessageText:
//
//  The attempted operation did not complete in the allotted time.
//
#define ZT_E_TIMEOUT                     0xC1120010L

//
// MessageId: ZT_E_NOT_LOGGED_IN
//
// MessageText:
//
//  The attempted operation requires the user to be logged on.
//
#define ZT_E_NOT_LOGGED_IN               0xC1120011L

//
// MessageId: ZT_E_INVALID_USER
//
// MessageText:
//
//  The attempted operation failed because the user specified was invalid
//
#define ZT_E_INVALID_USER                0xC1120012L

//
// MessageId: ZT_E_INVALID_ARG
//
// MessageText:
//
//  The attempted operation failed because the argument specified was invalid
//
#define ZT_E_INVALID_ARG                 0xC1120013L

//
// MessageId: ZT_E_ALREADY_EXISTS
//
// MessageText:
//
//  The item specified already exists.
//
#define ZT_E_ALREADY_EXISTS              0xC1120014L

//
// MessageId: ZT_E_ALREADY_CLOSED
//
// MessageText:
//
//  Attempted to close an object that was already closed previously.
//
#define ZT_E_ALREADY_CLOSED              0xC1120015L

//
// MessageId: ZT_E_ALREADY_LOGGED_IN
//
// MessageText:
//
//  User is already logged in.
//
#define ZT_E_ALREADY_LOGGED_IN           0xC1120016L

//
// MessageId: ZT_E_ATTRIBUTE_NOT_SET
//
// MessageText:
//
//  A required attribute was not set.
//
#define ZT_E_ATTRIBUTE_NOT_SET           0xC1120017L

//
// MessageId: ZT_E_REQUEST_DENIED
//
// MessageText:
//
//  Request was denied.
//
#define ZT_E_REQUEST_DENIED              0xC1120018L

//
// MessageId: ZT_E_TOO_MANY
//
// MessageText:
//
//  A Limit on the requested resource was reached.
//
#define ZT_E_TOO_MANY                    0xC1120019L


/////////////////////////////////////////////////////////////////////////
//
// ZoneTech Network Error Codes
//
/////////////////////////////////////////////////////////////////////////

//
// MessageId: ZT_E_CANNOT_INIT_WINSOCK
//
// MessageText:
//
//  Failed to initialize the Windows Sockets library.
//
#define ZT_E_CANNOT_INIT_WINSOCK         0xC1120400L

//
// MessageId: ZT_E_FAILED_TO_CONNECT
//
// MessageText:
//
//  Failed to connect to the specified server.
//
#define ZT_E_FAILED_TO_CONNECT           0xC1120401L

//
// MessageId: ZT_E_CONNECTION_CLOSED
//
// MessageText:
//
//  The connection was closed by one of the communicating parties.
//
#define ZT_E_CONNECTION_CLOSED           0xC1120402L

//
// MessageId: ZT_E_SEND_FAILED
//
// MessageText:
//
//  Failed to send data to the connected server.
//
#define ZT_E_SEND_FAILED                 0xC1120403L

//
// MessageId: ZT_E_NO_ADAPTER
//
// MessageText:
//
//  Failed to query information about the TCP/IP adapter.
//
#define ZT_E_NO_ADAPTER                  0xC1120404L

//
// MessageId: ZT_E_NOT_CONNECTED
//
// MessageText:
//
//  The connection is not established.
//
#define ZT_E_NOT_CONNECTED               0xC1120405L

//
// MessageId: ZT_E_WINSOCK_ERROR
//
// MessageText:
//
//  A unexpected winsock error occurred.  Use WSAGetLastError to retreive the specific error code.
//
#define ZT_E_WINSOCK_ERROR               0xC1120406L

//
// MessageId: ZT_E_RECEIVE_FAILED
//
// MessageText:
//
//  Failed to receive data from the connected server.
//
#define ZT_E_RECEIVE_FAILED              0xC1120407L

//
// MessageId: ZT_E_WAITMAX_EXCEEDED
//
// MessageText:
//
//  The Maximum number of pending operations has been exceeded.
//
#define ZT_E_WAITMAX_EXCEEDED            0xC1120408L

//
// MessageId: ZT_E_CONNECTION_DROPPED
//
// MessageText:
//
//  The connection was closed by the network.
//
#define ZT_E_CONNECTION_DROPPED          0xC1120409L

//
// MessageId: ZT_E_CONNECTION_CLOSED_SERVERINITIATED
//
// MessageText:
//
//  Temporary fine grain error code for debugging why we are dropping connections.
//
#define ZT_E_CONNECTION_CLOSED_SERVERINITIATED 0xC112040AL

//
// MessageId: ZT_E_CONNECTION_CLOSED_CLIENTINITIATED
//
// MessageText:
//
//  Temporary fine grain error code for debugging why we are dropping connections.
//
#define ZT_E_CONNECTION_CLOSED_CLIENTINITIATED 0xC112040BL

//
// MessageId: ZT_E_CONNECTION_SERVERBOOT
//
// MessageText:
//
//  Temporary fine grain error code for debugging why we are dropping connections.
//
#define ZT_E_CONNECTION_SERVERBOOT       0xC112040CL

//
// MessageId: ZT_E_CONNECTION_CLIENTDISCONNECT
//
// MessageText:
//
//  Temporary fine grain error code for debugging why we are dropping connections.
//
#define ZT_E_CONNECTION_CLIENTDISCONNECT 0xC112040DL

//
// MessageId: ZT_E_CONNECTION_DROPPED_GONE
//
// MessageText:
//
//  Temporary fine grain error code for debugging why we are dropping connections.
//
#define ZT_E_CONNECTION_DROPPED_GONE     0xC112040EL

//
// MessageId: ZT_E_CONNECTION_DROPPED_LOST
//
// MessageText:
//
//  Temporary fine grain error code for debugging why we are dropping connections.
//
#define ZT_E_CONNECTION_DROPPED_LOST     0xC112040FL


/////////////////////////////////////////////////////////////////////////
//
// ZoneTech Authentication Error Codes
//
/////////////////////////////////////////////////////////////////////////

//
// MessageId: ZT_E_AUTH_INVALID_STATUS
//
// MessageText:
//
//  The ZoneAuth Session status is not in an expected state.
//
#define ZT_E_AUTH_INVALID_STATUS         0xC1120800L

//
// MessageId: ZT_E_AUTH_PENDING
//
// MessageText:
//
//  The ZoneAuth Session has not yet completed authentication.
//
#define ZT_E_AUTH_PENDING                0xC1120801L

//
// MessageId: ZT_E_AUTH_TIMEOUT
//
// MessageText:
//
//  The ZoneAuth Session was failed because the connection was timed out by the client.
//
#define ZT_E_AUTH_TIMEOUT                0xC1120802L

//
// MessageId: ZT_E_AUTH_INVALID_PACKET
//
// MessageText:
//
//  The ZoneAuth Session received an invalid packet from the server.
//
#define ZT_E_AUTH_INVALID_PACKET         0xC1120803L

//
// MessageId: ZT_E_AUTH_USER_CANCEL
//
// MessageText:
//
//  The ZoneAuth Session was cancelled by the user.
//
#define ZT_E_AUTH_USER_CANCEL            0xC1120804L

//
// MessageId: ZT_E_AUTH_DENIED
//
// MessageText:
//
//  The ZoneAuth Session's credentials failed authentication.
//
#define ZT_E_AUTH_DENIED                 0xC1120805L

//
// MessageId: ZT_E_AUTH_INVALID_TICKET
//
// MessageText:
//
//  The ZoneAuth Ticket provided was invalid.
//
#define ZT_E_AUTH_INVALID_TICKET         0xC1120806L

//
// MessageId: ZT_E_AUTH_NO_CACHE
//
// MessageText:
//
//  There are no cache credentials to provide re-authentication against.
//
#define ZT_E_AUTH_NO_CACHE               0xC1120807L

//
// MessageId: ZT_E_AUTH_NO_LOGIN_INFO
//
// MessageText:
//
//  There is not previously stored login information.
//
#define ZT_E_AUTH_NO_LOGIN_INFO          0xC1120808L


/////////////////////////////////////////////////////////////////////////
//
// ZoneTech Match Error Codes
//
/////////////////////////////////////////////////////////////////////////

//
// MessageId: ZT_E_MATCH_NO_KEY
//
// MessageText:
//
//  The specified key does not exist.
//
#define ZT_E_MATCH_NO_KEY                0xC1120C00L

//
// MessageId: ZT_E_MATCH_NO_PLAYER
//
// MessageText:
//
//  The specified player ID does not exist.
//
#define ZT_E_MATCH_NO_PLAYER             0xC1120C01L

//
// MessageId: ZT_E_MATCH_PLAYER_EXISTS
//
// MessageText:
//
//  The specified player ID already exists.
//
#define ZT_E_MATCH_PLAYER_EXISTS         0xC1120C02L

//
// MessageId: ZT_E_MATCH_RONLY_ATTR
//
// MessageText:
//
//  Cannot assign to a read only attribute.
//
#define ZT_E_MATCH_RONLY_ATTR            0xC1120C03L

//
// MessageId: ZT_E_PROTOCOL_ERROR
//
// MessageText:
//
//  An error in the ZoneTech network protocol was encountered.
//
#define ZT_E_PROTOCOL_ERROR              0xC1120C04L

//
// MessageId: ZT_E_BAD_PROTOCOL_VER
//
// MessageText:
//
//  Incompatible Protocol version mismatch.
//
#define ZT_E_BAD_PROTOCOL_VER            0xC1120C05L

//
// MessageId: ZT_E_NO_QUERYSERVER
//
// MessageText:
//
//  The ZoneMatch Server for the specified Game GUID is not found.
//
#define ZT_E_NO_QUERYSERVER              0xC1120C06L

//
// MessageId: ZT_E_ALREADY_RUNNING
//
// MessageText:
//
//  Object is already running.
//
#define ZT_E_ALREADY_RUNNING             0xC1120C07L

//
// MessageId: ZT_E_CLOSED
//
// MessageText:
//
//  Object is closed.
//
#define ZT_E_CLOSED                      0xC1120C08L

//
// MessageId: ZT_E_INVALID_COLUMN
//
// MessageText:
//
//  Supplied column does not exist.
//
#define ZT_E_INVALID_COLUMN              0xC1120C09L

//
// MessageId: ZT_E_DISCONNECTED
//
// MessageText:
//
//  Client is disconnected from the server.
//
#define ZT_E_DISCONNECTED                0xC1120C0AL

//
// MessageId: ZT_E_NOT_READY
//
// MessageText:
//
//  The Object is not ready to perform the request operation at this time.
//
#define ZT_E_NOT_READY                   0xC1120C0BL

//
// MessageId: ZT_E_CANNOT_DELETE
//
// MessageText:
//
//  Cannot delete this attribute.
//
#define ZT_E_CANNOT_DELETE               0xC1120C0CL


/////////////////////////////////////////////////////////////////////////
//
// GUN2 Account HRESULTS
//
/////////////////////////////////////////////////////////////////////////

//
// MessageId: ZT_E_USERNAME_ALREADY_TAKEN
//
// MessageText:
//
//  Specified username is already in use.
//
#define ZT_E_USERNAME_ALREADY_TAKEN      0xC1121000L

//
// MessageId: ZT_E_INVALID_USERNAME_LENGTH
//
// MessageText:
//
//  The length of the user name is invalid.
//
#define ZT_E_INVALID_USERNAME_LENGTH     0xC1121001L

//
// MessageId: ZT_E_INVALID_USERNAME_OBSCENE
//
// MessageText:
//
//  The username was determined to contain obscenity.
//
#define ZT_E_INVALID_USERNAME_OBSCENE    0xC1121002L

//
// MessageId: ZT_E_INVALID_PASSWORD
//
// MessageText:
//
//  The password specified is invalid
//
#define ZT_E_INVALID_PASSWORD            0xC1121003L

//
// MessageId: ZT_E_INVALID_USERID
//
// MessageText:
//
//  The userid specified is invalid.
//
#define ZT_E_INVALID_USERID              0xC1121004L

//
// MessageId: ZT_E_ACCOUNT_LOCKED
//
// MessageText:
//
//  The account indicated is locked.
//
#define ZT_E_ACCOUNT_LOCKED              0xC1121005L

//
// MessageId: ZT_E_MAC_BANNED
//
// MessageText:
//
//  The machine address specified is invalid.
//
#define ZT_E_MAC_BANNED                  0xC1121006L

//
// MessageId: ZT_E_AUTHENTICATION_FAILURE
//
// MessageText:
//
//  The username and/or password specified is not valid.
//
#define ZT_E_AUTHENTICATION_FAILURE      0xC1121007L

//
// MessageId: ZT_E_CHANGED_TOO_RECENTLY
//
// MessageText:
//
//  Account changed too recently.
//
#define ZT_E_CHANGED_TOO_RECENTLY        0xC1121008L

//
// MessageId: ZT_E_ALREADY_IN_LIST
//
// MessageText:
//
//  An attempt was made to add a user to a list they are already on.
//
#define ZT_E_ALREADY_IN_LIST             0xC1121009L


/////////////////////////////////////////////////////////////////////////
//
// Friends HRESULTS
//
/////////////////////////////////////////////////////////////////////////

//
// MessageId: ZT_E_FAILED_LIST_ADD
//
// MessageText:
//
//  Attempt to add item to list failed unexpectedly. 
//
#define ZT_E_FAILED_LIST_ADD             0xC1121400L

//
// MessageId: ZT_E_NOT_IN_LIST
//
// MessageText:
//
//  Item not in list. 
//
#define ZT_E_NOT_IN_LIST                 0xC1121401L

//
// MessageId: ZT_E_NOT_REQUESTED
//
// MessageText:
//
//  The attempted operation was not requested by the target.
//
#define ZT_E_NOT_REQUESTED               0xC1121402L

//
// MessageId: ZT_E_DO_NOT_DISTURB
//
// MessageText:
//
//  The target user has their do not disturb state flag set.
//
#define ZT_E_DO_NOT_DISTURB              0xC1121403L

//
// MessageId: ZT_E_ALREADY_PENDING
//
// MessageText:
//
//  The operation is already pending and cannot be submitted again until it completes.
//
#define ZT_E_ALREADY_PENDING             0xC1121404L


/////////////////////////////////////////////////////////////////////////
//
// Chat HRESULTS
//
/////////////////////////////////////////////////////////////////////////

//
// MessageId: ZT_E_INVALID_ROOM
//
// MessageText:
//
//  The room specified doesn't exist.
//
#define ZT_E_INVALID_ROOM                0xC1121800L

//
// MessageId: ZT_E_ALREADY_IN_A_ROOM
//
// MessageText:
//
//  User is already in a chat room.
//
#define ZT_E_ALREADY_IN_A_ROOM           0xC1121801L    

//
// MessageId: ZT_E_NOT_INVITED
//
// MessageText:
//
//  User was not invited to join private chat room.
//
#define ZT_E_NOT_INVITED                 0xC1121802L    

//
// MessageId: ZT_E_ROOM_LIMIT
//
// MessageText:
//
//  User was not allowed to join chat room because limit of users in room has been reached.
//
#define ZT_E_ROOM_LIMIT                  0xC1121803L    


/////////////////////////////////////////////////////////////////////////
//
// ZoneTech XML Error Codes
//
/////////////////////////////////////////////////////////////////////////

//
// MessageId: ZT_E_XML_SYNTAX_ERROR
//
// MessageText:
//
//  An XML syntax error has be encountered.
//
#define ZT_E_XML_SYNTAX_ERROR            0xC1121C00L

//
// MessageId: ZT_E_TOO_MANY_ATTRIBUTES
//
// MessageText:
//
//  An XML tag has too many attribute fields.
//
#define ZT_E_TOO_MANY_ATTRIBUTES         0xC1121C01L

//
// MessageId: ZT_E_MISMATCHED_XML_TAGS
//
// MessageText:
//
//  The XML Start and End Tags do Not Match.
//
#define ZT_E_MISMATCHED_XML_TAGS         0xC1121C02L

//
// MessageId: ZT_E_INDEX_TOO_GREAT
//
// MessageText:
//
//  The index provided does not address a valid item.
//
#define ZT_E_INDEX_TOO_GREAT             0xC1121C03L

//
// MessageId: ZT_E_NOT_FOUND
//
// MessageText:
//
//  The requested named item was not found.
//
#define ZT_E_NOT_FOUND                   0xC1121C04L

//
// MessageId: ZT_E_NESTING_TOO_DEEP
//
// MessageText:
//
//  The nesting of tags exceeded the buffer space of the parser.
//
#define ZT_E_NESTING_TOO_DEEP            0xC1121C05L

//
// MessageId: ZT_E_BAD_AMP_CODE
//
// MessageText:
//
//  An incorrect Ampersand encoding was found in an XML string.
//
#define ZT_E_BAD_AMP_CODE                0xC1121C06L


#endif // _GUNERR_H_

