/*++

Copyright (c) 1999  Microsoft Corporation

Module Name:

    GunErr.h

Abstract:

    Definitions for ZoneTech error messages.

Author:


Revision History:

Notes:

    This file is generated by the MC tool from the ZoneTecherr.mc file.

--*/

#ifndef _ZONETECHRR_H_
#define _ZONETECHERR_H_


#define STATUS_SEVERITY(hr)  (((hr) >> 30) & 0x3)

// Customer Bit is set by the message compiler command line arguments

/////////////////////////////////////////////////////////////////////////
//
// ZoneTech General Error Codes
//
/////////////////////////////////////////////////////////////////////////

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//
#define FACILITY_ZONETECH                0x112
#define FACILITY_ZNULL                   0x0


//
// Define the severity codes
//
#define STATUS_SEVERITY_WARNING          0x2
#define STATUS_SEVERITY_SUCCESS          0x0
#define STATUS_SEVERITY_INFORMATIONAL    0x1
#define STATUS_SEVERITY_ERROR            0x3


//
// MessageId: ZT_E_VERSION_NOT_AVAIL
//
// MessageText:
//
//  The requested component version in not available.
//
#define ZT_E_VERSION_NOT_AVAIL           0xC1120001L

//
// MessageId: ZT_E_BUFFER_TOO_SMALL
//
// MessageText:
//
//  The provided buffer is too small to complete the operation.
//
#define ZT_E_BUFFER_TOO_SMALL            0xC1120002L

//
// MessageId: ZT_E_INTERNAL
//
// MessageText:
//
//  An internal error occurred.
//
#define ZT_E_INTERNAL                    0xC1120003L

//
// MessageId: ZT_E_INVALID_STATUS
//
// MessageText:
//
//  The ZoneTech object status is not in an expected state.
//
#define ZT_E_INVALID_STATUS              0xC1120004L

//
// MessageId: ZT_E_STR_TOO_LONG
//
// MessageText:
//
//  The string exceeds the maximum supported string length for this operation.
//
#define ZT_E_STR_TOO_LONG                0xC1120005L

//
// MessageId: ZT_E_PENDING
//
// MessageText:
//
//  The operation is pending.
//
#define ZT_E_PENDING                     0xC1120006L

//
// MessageId: ZT_E_ATTR_NOT_FOUND
//
// MessageText:
//
//  The Attribute was not found.
//
#define ZT_E_ATTR_NOT_FOUND              0xC1120007L

//
// MessageId: ZT_E_NOT_INITED
//
// MessageText:
//
//  The Init method for this object must be called before this operation.
//
#define ZT_E_NOT_INITED                  0xC1120008L

//
// MessageId: ZT_E_ALREADY_INITED
//
// MessageText:
//
//  The Init method cannot be called more than once on this object.
//
#define ZT_E_ALREADY_INITED              0xC1120009L

//
// MessageId: ZT_E_WRONG_THREAD
//
// MessageText:
//
//  Call to object was made on the wrong thread.
//
#define ZT_E_WRONG_THREAD                0xC112000AL

//
// MessageId: ZONE_E_ASSERT
//
// MessageText:
//
//  %1
//
#define ZONE_E_ASSERT                    0xC112000BL


/////////////////////////////////////////////////////////////////////////
//
// ZoneTech Network Error Codes
//
/////////////////////////////////////////////////////////////////////////

//
// MessageId: ZT_E_CANNOT_INIT_WINSOCK
//
// MessageText:
//
//  Failed to initialize the Windows Sockets library.
//
#define ZT_E_CANNOT_INIT_WINSOCK         0xC11203E8L

//
// MessageId: ZT_E_FAILED_TO_CONNECT
//
// MessageText:
//
//  Failed to connect to the specified server.
//
#define ZT_E_FAILED_TO_CONNECT           0xC11203E9L

//
// MessageId: ZT_E_CONNECTION_CLOSED
//
// MessageText:
//
//  The connection to the server was unexpectedly closed.
//
#define ZT_E_CONNECTION_CLOSED           0xC11203EAL

//
// MessageId: ZT_E_SEND_FAILED
//
// MessageText:
//
//  Failed to send data to the connected server.
//
#define ZT_E_SEND_FAILED                 0xC11203EBL

//
// MessageId: ZT_E_NO_ADAPTER
//
// MessageText:
//
//  Failed to query information about the TCP/IP adapter.
//
#define ZT_E_NO_ADAPTER                  0xC11203ECL

//
// MessageId: ZT_E_NOT_CONNECTED
//
// MessageText:
//
//  The connection is not established.
//
#define ZT_E_NOT_CONNECTED               0xC11203EDL

//
// MessageId: ZT_E_WINSOCK_ERROR
//
// MessageText:
//
//  A unexpected winsock error occurred.  Use WSAGetLastError to retreive the specific error code.
//
#define ZT_E_WINSOCK_ERROR               0xC11203EEL

//
// MessageId: ZT_E_RECEIVE_FAILED
//
// MessageText:
//
//  Failed to receive data from the connected server.
//
#define ZT_E_RECEIVE_FAILED              0xC11203EFL

//
// MessageId: ZT_E_WAITMAX_EXCEEDED
//
// MessageText:
//
//  The Maximum number of pending operations has been exceeded.
//
#define ZT_E_WAITMAX_EXCEEDED            0xC11203F0L


/////////////////////////////////////////////////////////////////////////
//
// ZoneTech Authentication Error Codes
//
/////////////////////////////////////////////////////////////////////////

//
// MessageId: ZT_E_AUTH_INVALID_STATUS
//
// MessageText:
//
//  The ZoneAuth Session status is not in an expected state.
//
#define ZT_E_AUTH_INVALID_STATUS         0xC11207D0L

//
// MessageId: ZT_E_AUTH_PENDING
//
// MessageText:
//
//  The ZoneAuth Session has not yet completed authentication.
//
#define ZT_E_AUTH_PENDING                0xC11207D1L

//
// MessageId: ZT_E_AUTH_TIMEOUT
//
// MessageText:
//
//  The ZoneAuth Session was failed because the connection was timed out by the client.
//
#define ZT_E_AUTH_TIMEOUT                0xC11207D2L

//
// MessageId: ZT_E_AUTH_INVALID_PACKET
//
// MessageText:
//
//  The ZoneAuth Session received an invalid packet from the server.
//
#define ZT_E_AUTH_INVALID_PACKET         0xC11207D3L

//
// MessageId: ZT_E_AUTH_USER_CANCEL
//
// MessageText:
//
//  The ZoneAuth Session was cancelled by the user.
//
#define ZT_E_AUTH_USER_CANCEL            0xC11207D4L

//
// MessageId: ZT_E_AUTH_DENIED
//
// MessageText:
//
//  The ZoneAuth Session's credentials failed authentication.
//
#define ZT_E_AUTH_DENIED                 0xC11207D5L

//
// MessageId: ZT_E_AUTH_INVALID_TICKET
//
// MessageText:
//
//  The ZoneAuth Ticket provided was invalid.
//
#define ZT_E_AUTH_INVALID_TICKET         0xC11207D6L

//
// MessageId: ZT_E_AUTH_NO_CACHE
//
// MessageText:
//
//  There are no cache credentials to provide re-authentication against.
//
#define ZT_E_AUTH_NO_CACHE               0xC11207D7L

//
// MessageId: ZT_E_AUTH_NO_LOGIN_INFO
//
// MessageText:
//
//  There is not previously stored login information.
//
#define ZT_E_AUTH_NO_LOGIN_INFO          0xC11207D8L


/////////////////////////////////////////////////////////////////////////
//
// ZoneTech Match Error Codes
//
/////////////////////////////////////////////////////////////////////////

//
// MessageId: ZT_E_MATCH_NO_KEY
//
// MessageText:
//
//  The specified key does not exist.
//
#define ZT_E_MATCH_NO_KEY                0xC11207D9L

//
// MessageId: ZT_E_MATCH_NO_PLAYER
//
// MessageText:
//
//  The specified player ID does not exist.
//
#define ZT_E_MATCH_NO_PLAYER             0xC11207DAL

//
// MessageId: ZT_E_MATCH_PLAYER_EXISTS
//
// MessageText:
//
//  The specified player ID already exists.
//
#define ZT_E_MATCH_PLAYER_EXISTS         0xC11207DBL

//
// MessageId: ZT_E_MATCH_RONLY_ATTR
//
// MessageText:
//
//  Cannot assign to a read only attribute.
//
#define ZT_E_MATCH_RONLY_ATTR            0xC11207DCL

//
// MessageId: ZT_E_PROTOCOL_ERROR
//
// MessageText:
//
//  An error in the ZoneTech network protocol was encountered.
//
#define ZT_E_PROTOCOL_ERROR              0xC11207DDL

//
// MessageId: ZT_E_BAD_PROTOCOL_VER
//
// MessageText:
//
//  Incompatible Protocol version mismatch.
//
#define ZT_E_BAD_PROTOCOL_VER            0xC11207DEL

//
// MessageId: ZT_E_NO_QUERYSERVER
//
// MessageText:
//
//  The ZoneMatch Server for the specified Game GUID is not found.
//
#define ZT_E_NO_QUERYSERVER              0xC11207DFL

//
// MessageId: ZT_E_ALREADY_RUNNING
//
// MessageText:
//
//  Object is already running.
//
#define ZT_E_ALREADY_RUNNING             0xC11207E0L

//
// MessageId: ZT_E_CLOSED
//
// MessageText:
//
//  Object is closed.
//
#define ZT_E_CLOSED                      0xC11207E1L

//
// MessageId: ZT_E_INVALID_COLUMN
//
// MessageText:
//
//  Supplied column does not exist.
//
#define ZT_E_INVALID_COLUMN              0xC11207E2L

//
// MessageId: ZT_E_DISCONNECTED
//
// MessageText:
//
//  Client is disconnected from the server.
//
#define ZT_E_DISCONNECTED                0xC11207E3L

//
// MessageId: ZT_E_NOT_READY
//
// MessageText:
//
//  The Object is not ready to perform the request operation at this time.
//
#define ZT_E_NOT_READY                   0xC11207E4L


/////////////////////////////////////////////////////////////////////////
//
// ZoneTech XML Parsing Error Codes
//
/////////////////////////////////////////////////////////////////////////

//
// MessageId: ZT_E_XML_SYNTAX_ERROR
//
// MessageText:
//
//  An XML syntax error has be encountered.
//
#define ZT_E_XML_SYNTAX_ERROR            0xC11207E5L

//
// MessageId: ZT_E_TOO_MANY_ATTRIBUTES
//
// MessageText:
//
//  An XML tag has too many attribute fields.
//
#define ZT_E_TOO_MANY_ATTRIBUTES         0xC11207E6L

//
// MessageId: ZT_E_MISMATCHED_XML_TAGS
//
// MessageText:
//
//  The XML Start and End Tags do Not Match.
//
#define ZT_E_MISMATCHED_XML_TAGS         0xC11207E7L


#endif // _ZONETECHERR_H_

