//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SiegeEditor.rc
//
#define IDD_ABOUTBOX                    100
#define ID_KEY_LEFT                     101
#define IDD_PROPPAGE_NODE_FADE_SETTINGS 102
#define ID_KEY_RIGHT                    102
#define ID_KEY_UP                       103
#define ID_KEY_DOWN                     104
#define IDC_POINTER_GO                  104
#define ID_KEY_DELETE                   105
#define IDC_POINTER_TRIGGER             105
#define IDD_PROPPAGE_PROPERTIES         106
#define IDC_POINTER_LIGHT               106
#define ID_OBJECT_OK_BUTTON             106
#define IDC_POINTER_GOGEN               107
#define IDC_CONSOLE_LISTVIEW            107
#define IDD_PROPPAGE_LIGHTING           107
#define IDC_POINTER_PARTY               108
#define ID_KEY_FORWARD                  108
#define IDC_POINTER_CAMERA              109
#define ID_KEY_BACKWARD                 109
#define IDC_POINTER_WAYPOINT            110
#define ID_ADDGOTOCUSTOMVIEW            110
#define ID_OBJECT_APPLY_BUTTON          111
#define ID_ATTACH_BUTTON                112
#define ID_PANE_NEXT                    113
#define ID_LIGHTING_IGNOREVERTEXCOLOR   114
#define IDB_SPLASH                      115
#define IDC_GRIDCONTROL                 116
#define ID_OBJECT_HIDE                  117
#define IDC_GRID_CONDITIONS             118
#define IDC_GRID_ACTIONS                119
#define ID_OBJECT_TRIGGERS_EXECUTE      120
#define ID_OBJECT_TRIGGERS_RESET        121
#define ID_OBJECT_CANCEL_BUTTON         122
#define ID_LINK_MODE                    123
#define ID_HITDETECTFLOORSONLY          124
#define ID_WIREFRAME                    125
#define ID_DOORDRAW                     126
#define ID_DRAWSTITCHDOORS              127
#define IDR_MAINFRAME                   128
#define ID_FLOORDRAW                    128
#define IDR_SIEGEETYPE                  129
#define ID_HOTPOINT_PROPERTIES          129
#define IDD_DIALOG_REGION_LOAD          130
#define ID_STARTINGPOS_PROPERTIES       130
#define ID_STARTINGPOS_CAMERASET        131
#define IDI_ICON1                       132
#define ID_STARTINGPOS_CAMERAPREVIEW    132
#define IDI_ICON2                       133
#define ID_HOTPOINT_INFORMATION         133
#define IDI_ICON3                       134
#define ID_GRAB_SCID                    134
#define IDI_ICON4                       135
#define ID_GRAB_GUID                    135
#define IDI_ICON5                       136
#define ID_DECAL_PROPERTIES             136
#define IDI_ICON6                       137
#define ID_CAMERA_SETTOGO               137
#define IDI_ICON7                       138
#define ID_CAMERA_GOSET                 138
#define IDI_ICON_3BOX                   138
#define IDI_ICON8                       139
#define ID_GRAB_LIGHT_GUID              139
#define IDI_ICON_BBOX                   139
#define IDI_ICON9                       140
#define IDC_SFX_GRIDCONTROL             140
#define IDI_ICON10                      141
#define ID_STARTINGPOS_PROPERTIES_INFO  141
#define IDI_ICON_CLOSE_FOLDER           141
#define IDI_ICON11                      142
#define IDC_SFX_PARAM_GRIDCONTROL       142
#define IDI_ICON_OPEN_FOLDER            142
#define IDI_ICON12                      143
#define ID_OBJECT_ROTATE_SELECTION      143
#define IDI_ICON13                      144
#define ID_OBJECT_NODE_POSITION_OVERRIDE 144
#define IDI_ICON14                      145
#define ID_VIEW_DEBUGHUDS_ALL           145
#define IDI_ICON15                      146
#define ID_VIEW_DEBUGHUDS_ACTORS        146
#define IDI_ICON16                      147
#define ID_VIEW_DEBUGHUDS_ITEMS         147
#define IDI_ICON_REDO                   147
#define IDI_ICON17                      148
#define ID_VIEW_DEBUGHUDS_COMMANDS      148
#define IDI_ICON_UNDO                   148
#define IDD_DIALOG_KEYBOARD_SETTINGS    149
#define ID_VIEW_DEBUGHUDS_MISC          149
#define IDD_DIALOG_NEW_MAP              150
#define ID_OBJECT_MOVEMENTLOCK_X        150
#define IDD_DIALOG_SAVE_REGION          151
#define ID_OBJECT_MOVEMENTLOCK_Y        151
#define IDD_DIALOG_REGION_NEW           152
#define ID_OBJECT_MOVEMENTLOCK_Z        152
#define IDD_DIALOG_FIND                 153
#define ID_OBJECT_MOVEMENTLOCK_NONE     153
#define IDD_DIALOG_LIGHTING_AMBIENCE    154
#define ID_OBJECT_DRAG_COPY             154
#define IDD_PROPPAGE_COLOR              155
#define ID_DECAL_GRAB_GUID              155
#define IDD_PROPPAGE_POSITION           156
#define ID_MISC_SET_FOCUS_MAIN          156
#define IDD_DIALOG_CONTENT_SEARCH       157
#define ID_OBJECT_HELP_BUTTON           157
#define IDD_DIALOG_PROGRESS_LOAD        158
#define ID_RENAMEFOLER                  158
#define IDD_DIALOG_MAP_SETTINGS         159
#define ID_PROPERTYSHEET_NODE_PROPERTIES 159
#define IDD_DIALOG_MESH_LIST            160
#define ID_PREFERENCE_DRAW_CAMERA_TARGET 160
#define IDD_DIALOG_NODE_SET             161
#define ID_PREFERENCE_RESTRICT_CAMERA   161
#define IDD_DIALOG_NODE_LIST            162
#define IDD_PROPPAGE_NODE_SET           164
#define IDD_PROPPAGE_NODE_STITCHING     165
#define IDD_DIALOG_PARTY_EDITOR         166
#define IDD_DIALOG_PARTY_CREATOR        167
#define IDD_DIALOG_PREFERENCES          168
#define IDD_DIALOG_PROGRESS_SAVE        169
#define IDD_DIALOG_STITCH_BUILDER       170
#define IDD_DIALOG_STITCH_MANAGER       171
#define IDD_DIALOG_TRIGGER_EDITOR       172
#define IDD_DIALOG_TRIGGER_ACTION_PROPERTIES 173
#define IDD_DIALOG_TRIGGER_CONDITION_PROPERTIES 174
#define IDD_DIALOG_TRIGGER_PROPERTIES   175
#define IDD_DIALOG_TRIGGER_VALUE        176
#define IDB_GPGLOGO                     177
#define IDD_PROPPAGE_OBJECT_INVENTORY   177
#define IDD_PROPPAGE_OBJECT_EQUIPMENT   178
#define IDD_DIALOG_LIGHTING_EDIT_DIRECTIONAL 179
#define IDR_MAINVIEW_MENU               180
#define IDR_CUSTOMVIEW_MENU             181
#define IDD_DIALOG_NEWFOLDER            182
#define IDD_PROPPAGE_NODE_GENERAL       183
#define IDD_PROPPAGE_NODE_MOOD          184
#define IDD_DIALOG_COLORS               185
#define IDI_ICON18                      187
#define IDI_ICON19                      188
#define IDI_ICON20                      189
#define IDI_ICON21                      190
#define IDI_ICON22                      191
#define IDB_BITMAP_HSB                  193
#define IDB_BITMAP_RGB                  194
#define IDD_DIALOG_LIGHTING_GOLIGHT     200
#define IDD_DIALOG_REGION_SETTINGS      201
#define IDD_DIALOG_OBJECT_SPOT_SNAPPER  202
#define IDD_DIALOG_OBJECT_VALIDATION    203
#define IDD_DIALOG_BOOKMARKS            204
#define IDR_TOOLBAR_VIEW                207
#define IDR_TOOLBAR_NODE                215
#define IDR_TOOLBAR_OBJECT              217
#define IDR_TOOLBAR_LIGHT               219
#define IDD_DIALOG_BATCH_LNC_GENERATION 221
#define IDD_DIALOG_STARTING_POSITIONS   222
#define IDR_TOOLBAR_CAMERA              252
#define IDD_DIALOG_TRIGGER_PROP         256
#define IDD_DIALOG_CONVERSATION_EDITOR  258
#define IDD_DIALOG_CONVERSATION_MANAGER 259
#define IDD_DIALOG_OBJECT_TEMPLATE_PROPERTIES 261
#define IDR_TOOLBAR_MODE                262
#define IDD_DIALOG_MAP_HOTPOINTS        266
#define IDD_DIALOG_REGION_EDIT_HOTPOINTS 267
#define IDD_DIALOG_MAP_NEW_HOTPOINT     268
#define IDD_DIALOG_REGION_HOTPOINT_DIRECTION 270
#define IDB_BITMAP_SPLASH               272
#define IDD_DIALOG_OBJECT_TEMPLATE      273
#define IDD_DIALOG_OBJECT_LIST          274
#define IDD_DIALOG_TRIGGERS             275
#define IDD_DIALOG_HUDS                 276
#define IDD_DIALOG_ADD_CONDITION        277
#define IDD_DIALOG_ADD_ACTION           278
#define IDD_PROPPAGE_PROPERTIES_TEMPLATE 279
#define IDD_PROPPAGE_PROPERTIES_TRIGGERS 280
#define IDD_PROPPAGE_PROPERTIES_LIGHTING 281
#define IDD_PROPPAGE_PROPERTIES_INVENTORY 282
#define IDD_PROPPAGE_PROPERTIES_EQUIPMENT 283
#define IDD_PROPPAGE_PROPERTIES_ROTATION 284
#define IDC_CURSOR_LINK                 284
#define IDC_POINTER_SP                  286
#define IDI_ICON23                      286
#define IDI_ICON_HOTPOINT               286
#define IDC_POINTER_HP                  287
#define IDI_ICON24                      287
#define IDC_POINTER_DECAL               288
#define IDI_ICON25                      288
#define IDD_DIALOG_HOTPOINT_PROPERTIES  289
#define IDD_DIALOG_REGION_NEW_HOTPOINT  290
#define IDD_DIALOG_HOTPOINT_INFORMATION 291
#define IDD_DIALOG_COMMAND_EDITOR       296
#define IDD_DIALOG_DECAL                297
#define IDD_DIALOG_DECAL_PREFERENCES    298
#define IDD_DIALOG_CAMERA_CONTROLLER    299
#define IDD_DIALOG_PATH_MAKER           302
#define IDD_DIALOG_PATH_REPORTER        303
#define IDD_DIALOG_PATH_NEW             304
#define IDD_DIALOG_SFX                  307
#define IDD_DIALOG_NEW_SFX              308
#define IDD_DIALOG_LOAD_SFX             309
#define IDD_DIALOG_STARTING_POSITION_PROPERTIES 310
#define IDD_DIALOG_SELECTION_FILTERS    312
#define IDD_DIALOG_SFX_PARAMETERS       314
#define IDD_DIALOG_LOGICALNODE_PROPERTIES 315
#define IDR_MENU_PREVIEWER              316
#define IDD_DIALOG_PORTRAITS            317
#define IDD_PROPPAGE_PROPERTIES_GIZMO   319
#define IDD_DIALOG_MOVE_LOCK            322
#define IDD_DIALOG_BOOKMARK_LIST        323
#define IDD_DIALOG_BOOKMARK_PROPERTIES  324
#define IDD_DIALOG_HIDE_COMPONENTS      325
#define IDD_DIALOG_SCID_REMAPPER        326
#define IDD_DIALOG_LOAD_CUSTOM_VIEW     327
#define IDD_DIALOG_SAVE_CUSTOM_VIEW     328
#define IDD_DIALOG_ITEM_VIEWER          329
#define IDD_DIALOG_PATH_BATCH_GENERATION 330
#define IDD_DIALOG_OBJECT_GROUPING      331
#define IDD_DIALOG_OBJECT_GROUPING_NEW  332
#define IDD_DIALOG_MACROS               333
#define IDD_DIALOG_NEW_MACRO            334
#define IDD_DIALOG_OBJECT_NEXT          335
#define IDD_DIALOG_NEW_MESH_GROUP       336
#define IDD_DIALOG_NODE_FADE_GROUPS     337
#define IDD_DIALOG_NEW_NODE_FADE_GROUP  338
#define IDD_DIALOG_STARTING_GROUPS      339
#define IDD_DIALOG_STARTING_GROUP_NEW   340
#define IDD_DIALOG_STARTING_GROUP_PROPERTIES 341
#define IDR_TOOLBAR_PREFERENCES         371
#define IDD_CAMERA                      373
#define IDI_ICON_GO                     381
#define IDI_ICON_SN                     382
#define IDI_ICON_DECAL                  383
#define IDI_ICON_LIGHT                  384
#define IDI_ICON_REGION                 385
#define IDI_ICON_STARTINGPOS            386
#define IDI_ICON_WORLD                  387
#define IDI_ICON_GIZMO                  388
#define IDI_ICON_SPOTLIGHT              390
#define IDD_DIALOG_STARTING_GROUP_ADD_LEVEL 391
#define IDD_DIALOG_CONVERSATION_LINE_EDITOR 392
#define IDD_DIALOG_CONVERSATION_ACTIVATE_QUESTS 393
#define IDD_DIALOG_CONVERSATION_COMPLETE_QUESTS 394
#define IDD_DIALOG_CUSTOM_BUTTONS       395
#define IDD_DIALOG_CONVERSATION_NEW     396
#define IDD_DIALOG_CONVERSATION_ADD_GOODBYE 397
#define IDD_DIALOG_CONVERSATION_LIST_GLOBAL 398
#define IDD_DIALOG_CONVERSATION_NEW_GLOBAL 399
#define ID_FILE_SAVEMAPAS               400
#define ID_FILE_SAVEFOLDERAS            401
#define IDD_DIALOG_SAVE_AS_DSMAP        402
#define IDD_DIALOG_SAVE_AS_DSMOD        403
#define IDD_DIALOG_BUILD_TANK_PROGRESS  404
#define ID_FILE_EXTRACT_TANK            407
#define IDD_DIALOG_EXTRACT_TANK         408
#define IDD_DIALOG_QUEST_MANAGER        409
#define IDD_DIALOG_QUEST_ADD            410
#define IDD_DIALOG_QUEST_CHAPTER_ADD    411
#define IDD_DIALOG_QUEST_EDITOR         412
#define IDD_DIALOG_QUEST_UPDATE         413
#define IDD_DIALOG_QUEST_CHAPTER_EDITOR 415
#define IDD_DIALOG_QUEST_CHAPTER_UPDATE 416
#define IDD_DIALOG_STITCH_TOOL          417
#define IDD_DIALOG_NODE_MATCHES         418
#define IDD_DIALOG_NODE_MATCH_PROGRESS  419
#define IDD_DIALOG_CUSTOM_VIEW_RENAME   420
#define IDD_DIALOG_MOOD_EDITOR          421
#define IDD_DIALOG_MOOD_FOG             422
#define IDD_DIALOG_MOOD_GENERAL         423
#define IDD_DIALOG_MOOD_WEATHER         425
#define IDD_DIALOG_MOOD_MUSIC           426
#define IDD_DIALOG_MOOD_ADD             427
#define IDD_DIALOG_MOOD_ADD_FOLDER      428
#define IDD_DIALOG_RESOURCE_TREE        429
#define IDD_DIALOG_GRID_SETTINGS        430
#define IDD_DIALOG_METER_POINT_EDITOR   433
#define IDD_DIALOG_VISUAL_NODE_PLACEMENT_SETTINGS 434
#define IDC_REGION_TREE                 1000
#define IDC_STATIC_RGB_RECT             1000
#define IDC_CHECK_FORCE_LNC_RECALC      1001
#define IDC_STATIC_HSB_RECT             1001
#define IDC_LIST_COMMANDS               1002
#define IDC_EDIT_RED                    1002
#define IDC_EDIT_KEY                    1003
#define IDC_ACTORLIST                   1003
#define IDC_SPIN_RED                    1003
#define IDC_EDIT_GREEN                  1004
#define IDC_RADIO_CONTROL               1005
#define IDC_SPIN_GREEN                  1005
#define IDC_RADIO_ALT                   1006
#define IDC_EDIT_BLUE                   1006
#define IDC_RADIO_SHIFT                 1007
#define IDC_SPIN_BLUE                   1007
#define IDC_EDIT1                       1008
#define IDC_EDIT_X                      1008
#define IDC_EDIT_FUELNAME               1008
#define IDC_STATIC_OLD                  1008
#define IDC_EDIT_GUID                   1008
#define IDC_EDIT_NAME                   1008
#define IDC_EDIT_NODE                   1008
#define IDC_EDIT_TEMPLATE_NAME          1008
#define IDC_EDIT_DELAY                  1008
#define IDC_EDIT_HOTPOINT_ID            1008
#define IDC_EDIT_HORIZONTAL             1008
#define IDC_EDIT_TRANSLATION            1008
#define IDC_EDIT_PATH                   1008
#define IDC_EDIT_RADIUS                 1008
#define IDC_EDIT_SCREEN_NAME            1008
#define IDC_EDIT_SOURCE                 1008
#define IDC_EDIT_STARTING_POSITION      1008
#define IDC_EDIT_ROTATION_SNAP_INCREMENT 1008
#define IDC_EDIT_COMPONENT              1008
#define IDC_EDIT_SCID_RANGE             1008
#define IDC_EDIT_CUSTOM_VIEW            1008
#define IDC_EDIT_MACRO_NAME             1008
#define IDC_EDIT_MINIMUM_MULTIPLIER     1008
#define IDC_EDIT_SCALE_MIN              1008
#define IDC_EDIT_SECTION                1008
#define IDC_EDIT_THANKS                 1008
#define IDC_EDIT_STITCH                 1008
#define IDC_EDIT_SEARCH_LEVEL           1008
#define IDC_EDIT_MOOD_NAME              1008
#define IDC_EDIT_AMBIENT_SOUND          1008
#define IDC_EDIT_SIZE                   1008
#define IDC_EDIT_SNAP_SENSITIVITY       1008
#define IDC_EDIT2                       1009
#define IDC_EDIT_Y                      1009
#define IDC_EDIT_SCREENNAME             1009
#define IDC_STATIC_NEW                  1009
#define IDC_EDIT_GOLIGHT_SCID           1009
#define IDC_EDIT_BOOKMARK               1009
#define IDC_EDIT_RESET_DELAY            1009
#define IDC_CAMERA_NODE                 1009
#define IDC_EDIT_HOTPOINT_NAME          1009
#define IDC_EDIT_VERTICAL               1009
#define IDC_EDIT_ROTATION               1009
#define IDC_EDIT_TOLERANCE              1009
#define IDC_EDIT_DEST                   1009
#define IDC_EDIT_TEMPLATE               1009
#define IDC_EDIT_MAXIMUM_MULTIPLIER     1009
#define IDC_EDIT_SCALE_MAX              1009
#define IDC_EDIT_LEVEL                  1009
#define IDC_EDIT_VALUE_1                1009
#define IDC_SOURCE_FOLDER_CHOICE        1009
#define IDC_STATUS                      1009
#define IDC_EDIT_SNO                    1009
#define IDC_EDIT_TRANSITION_TIME        1009
#define IDC_EDIT_AMBIENT_INTRO_DELAY    1009
#define IDC_EDIT_INTERVAL               1009
#define IDC_EDIT_SNAP_DELAY             1009
#define IDC_PROGRESS_SAVE               1010
#define IDC_EDIT_HUE                    1010
#define IDC_EDIT_MAGNITUDE_Z            1010
#define IDC_EDIT_DISTANCE               1010
#define IDC_EDIT_TEXT_2                 1010
#define IDC_EDIT_DOOR                   1010
#define IDC_EDIT_STANDARD_SOUND         1010
#define IDC_STATIC_INFO                 1011
#define IDC_PROGRESS_LOAD_BAR2          1011
#define IDC_SPIN_HUE                    1011
#define IDC_EDIT_CUSTOM_SCRIPT          1011
#define IDC_EDIT_VALUE_2                1011
#define IDC_EDIT_STANDARD_INTRO_DELAY   1011
#define IDC_SLIDER1                     1012
#define IDC_SLIDER_Y                    1012
#define IDC_EDIT_SAT                    1012
#define IDC_EDIT_BATTLE_SOUND           1012
#define IDC_SLIDER2                     1013
#define IDC_SLIDER_X                    1013
#define IDC_SPIN_SAT                    1013
#define IDC_EDIT_BATTLE_INTRO_DELAY     1013
#define IDC_SLIDER3                     1014
#define IDC_SLIDER_Z                    1014
#define IDC_EDIT_VAL                    1014
#define IDC_EDIT3                       1015
#define IDC_EDIT_Z                      1015
#define IDC_EDIT_SCID                   1015
#define IDC_SPIN_VAL                    1015
#define IDC_EDIT_MAGNITUDE_X            1015
#define IDC_EDIT_NOTES                  1015
#define IDC_EDIT_DOCUMENTATION          1015
#define IDC_EDIT_POLL_FREQUENCY         1015
#define IDC_EDIT_SNAP_INCREMENT         1015
#define IDC_EDIT_OBJECT                 1015
#define IDC_EDIT_LOD                    1015
#define IDC_EDIT_TEXT_SCROLL_RATE       1015
#define IDC_EDIT_SPEAKER                1015
#define IDC_EDIT_NEAR_DISTANCE          1015
#define IDC_EDIT_AMBIENT_REPEAT_DELAY   1015
#define IDC_EDIT_ORIGIN_X               1015
#define IDC_TREE_PROPERTIES             1016
#define IDC_EDIT_DIR_Z                  1016
#define IDC_EDIT_LD_NEAR_DISTANCE       1016
#define IDC_EDIT_STANDARD_REPEAT_DELAY  1016
#define IDC_EDIT_COLOR                  1017
#define IDC_EDIT_BATTLE_REPEAT_DELAY    1017
#define IDC_EDIT4                       1018
#define IDC_EDIT_SCALE                  1018
#define IDC_EDIT_MAGNITUDE_Y            1018
#define IDC_EDIT_REGION_GUID            1018
#define IDC_EDIT_DOC                    1018
#define IDC_EDIT_ICON_NAME              1018
#define IDC_EDIT_OCCUPANTS              1018
#define IDC_EDIT_FAR_DISTANCE           1018
#define IDC_EDIT_WIND_DIRECTION         1018
#define IDC_EDIT_ORIGIN_Y               1018
#define IDC_BUTTON_COLOR_STANDARD       1019
#define IDC_EDIT_LD_FAR_DISTANCE        1019
#define IDC_BUTTON_COLOR_ADVANCED       1020
#define IDC_PROGRESS_LOAD_BAR1          1021
#define IDC_LIST1                       1022
#define IDC_LIST_MOOD                   1022
#define IDC_LIST_ITEMS                  1022
#define IDC_LIST_SCRIPTS                1022
#define IDC_LIST_BOOKMARKS              1022
#define IDC_LIST_ACTORS                 1022
#define IDC_LIST_CONDITIONS             1022
#define IDC_LIST_OBJECTS                1022
#define IDC_LIST_SEARCH_RESULTS         1022
#define IDC_LIST_LOGICAL_FLAGS          1022
#define IDC_LIST_COMPONENTS             1022
#define IDC_LIST_CUSTOM_VIEWS           1022
#define IDC_LIST_MACROS                 1022
#define IDC_LIST_TEXTURES               1022
#define IDC_LIST_FADES                  1022
#define IDC_LIST_STARTING_GROUPS        1022
#define IDC_LIST_LEVELS                 1022
#define IDC_LIST_LINES                  1022
#define IDC_LIST_CONVERSATIONS          1022
#define IDC_MAP_CHOICE                  1022
#define IDC_LIST_REGION_INFO            1022
#define IDC_CLOSE                       1023
#define IDC_BUTTON1                     1023
#define IDC_REMOVEALLMEMBERS            1023
#define IDC_BUTTON_REMOVE_ALL           1023
#define IDC_REMOVE                      1023
#define IDC_BUTTON_SELECT_NODE          1023
#define IDC_BUTTON_ADD_MOOD             1023
#define IDC_BUTTON_GOLIGHT              1023
#define IDC_BUTTON_DELETE_GOLIGHT       1023
#define IDC_BUTTON_SNAP                 1023
#define IDC_BUTTON_VALIDATE_MAP         1023
#define IDC_BUTTON_USE_SELECTED_NODE    1023
#define IDC_BUTTON_FINDFIRST            1023
#define IDC_BUTTON_NEWCONDITION         1023
#define IDC_LIST_GOODBYES               1023
#define IDC_REPLACEALL                  1024
#define IDC_LIST2                       1024
#define IDC_ADDMEMBER                   1024
#define IDC_REMOVEALL                   1024
#define IDC_LIST_NODE                   1024
#define IDC_LIST_SPOTS                  1024
#define IDC_BUTTON_NEWACTION            1024
#define IDC_SUPERGRID                   1024
#define IDC_BUTTON_USE_SELECTED_NODE_CAMERA 1024
#define IDC_BUTTON_OBJECT_COLOR         1024
#define IDC_BUTTON_CUSTOM_BUTTONS       1024
#define IDC_LIST_CHAPTERS               1024
#define IDC_BUTTON_STANDARD_SOUND_FILES 1024
#define IDC_FIND                        1025
#define IDC_BUTTON_STITCH_MANAGER       1025
#define IDC_PARTY_MEMBER_TARGET_NODE    1025
#define IDC_COMBO1                      1025
#define IDC_LIST_CURRENT_INVENTORY      1025
#define IDC_COMBO_EQUIPSLOT             1025
#define IDC_COMBO_AVAILABLE_SCRIPTS     1025
#define IDC_LIST_ACTIONS                1025
#define IDC_BUTTON_ACTOR_COLOR          1025
#define IDC_BUTTON_BATTLE_SOUND_FILES   1025
#define IDC_EDIT_MAP_NAME               1026
#define IDC_LIST_AVAILABLE_INVENTORY    1026
#define IDC_COMBO_DEGREES_Y             1026
#define IDC_ADD                         1027
#define IDC_EDIT_DESCRIPTION            1027
#define IDC_COMBO_DEGREES_Z             1027
#define IDC_CONTENT_COMBO               1028
#define IDC_CONTENT_TYPE                1028
#define IDC_REGIONSELECT                1028
#define IDC_COMBO_SET                   1028
#define IDC_STITCH_REGION               1028
#define IDC_PARTYCOMBO                  1028
#define IDC_PARTYBRAIN                  1028
#define IDC_COMBO_PARAMETER             1028
#define IDC_RADIO_NONE                  1028
#define IDC_COMBO_VERSION               1029
#define IDC_ASSIGN                      1029
#define IDC_FADERELATE                  1030
#define IDC_EDIT_FOLDERNAME             1030
#define IDC_BUTTON_SELECT_MESH          1031
#define IDC_LIST_MESH                   1032
#define IDC_COMBO_CONTENT_DISPLAY       1033
#define IDC_LIST_MESH_GROUPS            1033
#define IDC_EDIT_NODE_GUID              1034
#define IDC_EDIT_MESH_GUID              1035
#define IDC_EDIT_SNO_FILENAME           1036
#define IDC_EDIT_PRECISION_AMOUNT       1037
#define IDC_EDIT_ZOOM_RATE              1038
#define IDC_BUTTON_REMOVE_MOOD          1039
#define IDC_BUTTON_REMOVE_ALL_MOODS     1040
#define IDC_COMBO_MOOD                  1042
#define IDC_EDIT_COLOR_RED              1043
#define IDC_EDIT_COLOR_GREEN            1044
#define IDC_EDIT_COLOR_BLUE             1045
#define IDC_MAPNAME                     1047
#define IDC_REGIONNAME                  1048
#define IDC_EDIT_ORADIUS                1048
#define IDC_EDIT_INTENSITY              1049
#define IDC_CHECK_INITIALLY_ACTIVE      1050
#define IDC_CHECK_ACTIVE                1051
#define IDC_CHECK_DRAWSHADOWS           1052
#define IDC_BUTTON_ADD_SCRIPT           1054
#define IDC_BUTTON_REMOVE_SCRIPT        1055
#define IDC_BUTTON_REMOVE_ALL_SCRIPTS   1056
#define IDC_EDIT_DIR_X                  1060
#define IDC_EDIT_DIR_Y                  1061
#define IDC_EDIT_IRADIUS                1062
#define IDC_CHECK_OCCLUDE               1063
#define IDC_BUTTON_VALIDATE_ALL         1064
#define IDC_BUTTON_VALIDATE_ALL_SCIDS   1065
#define IDC_BUTTON_NEW                  1066
#define IDC_BUTTON_SET_DATA             1068
#define IDC_BUTTON2                     1069
#define IDC_WIREFRAME                   1070
#define IDC_BUTTON3                     1070
#define IDC_DOORDRAW                    1071
#define IDC_STATIC_VERSION              1071
#define IDC_BUTTON_EDITACTION           1071
#define IDC_BUTTON_DESTINATION_ID_COLOR 1071
#define IDC_TERRAIN_AMBIENCE            1072
#define IDC_CONTENTBLOCKNAME            1072
#define IDC_STITCH_ORDER                1072
#define IDC_PARTYNAME                   1072
#define IDC_EDIT_PARAMETER              1072
#define IDC_BUTTON_REMOVEACTION         1072
#define IDC_BUTTON_REMOVE_GOODBYE       1072
#define IDC_EAST                        1073
#define IDC_AREALEVEL                   1073
#define IDC_COMBO_PLAYER                1073
#define IDC_NODELEVEL                   1073
#define IDC_TERRAIN_AMBIENT_COLOR       1073
#define IDC_AREAOBJECT                  1074
#define IDC_NODEOBJECT                  1074
#define IDC_CAMERA_Z                    1074
#define IDC_UP                          1075
#define IDC_COMBO_NODESET               1075
#define IDC_BUTTON_APPLY                1075
#define IDC_DISTANCE                    1076
#define IDC_COMBO_NODEVERSION           1076
#define IDC_FLOORDRAW                   1076
#define IDC_BUTTON_PREVIEW              1077
#define IDC_CAMERA_Y                    1077
#define IDC_BUTTON_SETDATA              1078
#define IDC_FOV                         1079
#define IDC_EDIT_ID                     1079
#define IDC_MINDISTANCE                 1080
#define IDC_LIST_POSITIONS              1080
#define IDC_MAXDISTANCE                 1081
#define IDC_CHECK_FPS                   1081
#define IDC_MINAZIMUTH                  1082
#define IDC_CHECK_LOADLIGHTS_GAS        1082
#define IDC_MAXAZIMUTH                  1083
#define IDC_CHECK_FULLSAVE              1083
#define IDC_NEARCLIP                    1084
#define IDC_CHECK_DELETELNC             1084
#define IDC_FARCLIP                     1085
#define IDC_ORBIT                       1086
#define IDC_SPIN1                       1086
#define IDC_SPIN_X                      1086
#define IDC_SPIN_FORWARDBACKWARD        1086
#define IDC_SPIN_RADIUS                 1086
#define IDC_AZIMUTH                     1087
#define IDC_SPIN2                       1087
#define IDC_SPIN_Y                      1087
#define IDC_SPIN3                       1088
#define IDC_SPIN_Z                      1088
#define IDC_SPIN_LEFTRIGHT              1089
#define IDC_SPIN4                       1089
#define IDC_SPIN_SCALE                  1089
#define IDC_SPIN5                       1090
#define IDC_CHECK_ONESHOT               1091
#define IDC_BUTTON_EDITCONDITION        1092
#define IDC_SPIN_AZIMUTH                1092
#define IDC_NORTH                       1093
#define IDC_BUTTON_REMOVECONDITON       1093
#define IDC_SPIN_ORBIT                  1093
#define IDC_CAMERA_X                    1094
#define IDC_SPIN_INOUT                  1094
#define IDC_CHECK_AFFECT_ACTORS         1095
#define IDC_SPIN_ORBIT_SNAP             1095
#define IDC_CHECK_AFFECT_ITEMS          1096
#define IDC_SPIN_AZIMUTH_SNAP           1096
#define IDC_CHECK_AFFECT_TERRAIN        1097
#define IDC_BOXES                       1098
#define IDC_CHECK_HIDE                  1098
#define IDC_DLIGHTS                     1099
#define IDC_SLIGHTS                     1100
#define IDC_DSHADOWS                    1101
#define IDC_SSHADOWS                    1102
#define IDC_DSHADING                    1103
#define IDC_SSHADING                    1104
#define IDC_IGNOREVERTEXCOLOR           1105
#define IDC_DISABLE                     1107
#define IDC_CHECK_ONTIMER               1107
#define IDC_COMBO_MINUTES               1108
#define IDC_COMBO_HOURS                 1109
#define IDC_EDIT_PITCH                  1110
#define IDC_EDIT_YAW                    1111
#define IDC_EDIT_ROLL                   1112
#define IDC_CHECK_FLIPFLOP              1114
#define IDC_CHECK_WHENFALSE             1115
#define IDC_LIST_HOTPOINTS              1116
#define IDC_BUTTON_PLACE_LOCAL          1117
#define IDC_BUTTON_PLACE_DIRECTIONAL    1118
#define IDC_CURR_INVENTORY              1119
#define IDC_BUTTON_EDIT_DIRECTIONAL     1119
#define IDC_INVENTORY_OBJECTS           1120
#define IDC_BUTTON_VALIDATE_TEMPLATES   1120
#define IDC_TREE_COMPONENTS             1121
#define IDC_STATIC_FIELDS               1124
#define IDC_STATIC_COMPONENTS           1125
#define IDC_BUTTON_SELECT               1126
#define IDC_BUTTON_DELETE               1127
#define IDC_COMBO_KEY                   1128
#define IDC_ONESHOT                     1129
#define IDC_BUTTON_DESELECT             1129
#define IDC_BUTTON_DESELECT_ALL         1130
#define IDC_BUTTON_VALIDATE_BOOKMARKS   1131
#define IDC_CHECK_WATERDRAW             1132
#define IDC_CHECK_LOGICALNODEDRAW       1133
#define IDC_CHECK_DRAWNORMALS           1134
#define IDC_TREE_TRIGGERS               1135
#define IDC_BUTTON_REMOVE_ACTIONS       1136
#define IDC_FADETYPE                    1137
#define IDC_BUTTON_NEW_TRIGGER          1137
#define IDC_AREAID                      1138
#define IDC_NODESECTION                 1138
#define IDC_BUTTON_REMOVE_TRIGGER       1138
#define IDC_ROOTNODES                   1139
#define IDC_CHECK_ONE_SHOT              1139
#define IDC_POLYSTATS                   1140
#define IDC_STATIC_TRIGGERS             1141
#define IDC_STATIC_PROPERTIES           1142
#define IDC_STATIC_CONDITIONS           1143
#define IDC_STATIC_REPLACE_CONDITIONS   1144
#define IDC_STATIC_REPLACE_ACTIONS      1145
#define IDC_STATIC_ACTIONS              1146
#define IDC_BUTTON_ADD_CONDITION        1147
#define IDC_BUTTON_REMOVE_CONDITION     1148
#define IDC_BUTTON_ADD_ACTION           1149
#define IDC_BUTTON_OPEN                 1150
#define IDC_CHECK_ACTORS                1151
#define IDC_CHECK_ITEMS                 1152
#define IDC_CHECK_MISC                  1153
#define IDC_CHECK_ALL                   1154
#define IDC_EFFECTS                     1155
#define IDC_CHECK_UPDATE_WORLD          1156
#define IDC_CHECK_DRAW_STITCH_DOORS     1157
#define IDC_STATIC_RESET_DELAY          1158
#define IDC_COMBO_CONDITONS             1159
#define IDC_COMBO_ACTIONS               1160
#define IDC_CHECK_GAMEOBJECTS           1161
#define IDC_CHECK_NODES                 1162
#define IDC_CHECK_LIGHTS                1163
#define IDC_CHECK_STITCHDATA            1164
#define IDC_CHECK_HOTPOINTS             1165
#define IDC_STATIC_TEMPLATE             1166
#define IDC_STATIC_SCID                 1167
#define IDC_CHECK_UPDATEWEATHER         1168
#define IDC_CHECK_UPDATESOUND           1169
#define IDC_STATIC_REPLACE              1171
#define IDC_COMBO_DEGREES_X             1172
#define IDC_STATIC_X                    1173
#define IDC_STATIC_Y                    1174
#define IDC_STATIC_Z                    1175
#define IDC_COMBO_ITEMS                 1176
#define IDC_STATIC_ITEMS                1177
#define IDC_STATIC_EQUIPPED             1178
#define IDC_STATIC_EQUIPSLOT            1179
#define IDC_RADIO_TEMPLATE              1180
#define IDC_RADIO_SCREEN_NAME           1181
#define IDC_RADIO_DOCUMENTATION         1182
#define IDC_FIND_NEXT                   1183
#define IDC_STATIC_SCREEN_NAME          1183
#define IDC_OBJECT_AMBIENCE             1184
#define IDC_CONTENTDESCRIPTION          1184
#define IDC_PARTYDESCRIPTION            1184
#define IDC_RESET_DELAY                 1184
#define IDC_STATIC_DOCUMENTATION        1184
#define IDC_CONTENTSCREENNAME           1185
#define IDC_ACTOR_AMBIENCE              1185
#define IDC_OBJECT_AMBIENT_COLOR        1186
#define IDC_ACTOR_AMBIENT_COLOR         1187
#define IDC_STATIC_INVENTORY            1188
#define IDC_STATIC_DISPLAY              1189
#define IDC_STATIC_DIRECTION            1190
#define IDC_STATIC_SETTINGS             1191
#define IDC_STATIC_IRADIUS              1192
#define IDC_STATIC_GREEN                1193
#define IDC_STATIC_ORADIUS              1194
#define IDC_STATIC_INTENSITY            1195
#define IDC_STATIC_RED                  1196
#define IDC_STATIC_BLUE                 1197
#define IDC_STATIC_VALUES               1198
#define IDC_STATIC_FINAL                1199
#define IDC_STATIC_OPTIONS              1200
#define IDC_CHECK_FLOORSONLY            1201
#define IDC_STATIC_SELECTED             1203
#define IDC_COMBO_SELECTED              1204
#define IDC_NONE                        1205
#define IDC_ACTORS                      1206
#define IDC_ITEMS                       1207
#define IDC_COMMANDS                    1208
#define IDC_MISC                        1209
#define IDC_ALL                         1210
#define IDC_CONTENTLIST                 1211
#define IDC_AI_SENSORS                  1211
#define IDC_AI_PATHFINDER               1212
#define IDC_BUTTON_ADD_CUSTOM           1212
#define IDC_MESSAGES                    1213
#define IDC_STATIC_SCREENNAME           1213
#define IDC_LABELS                      1214
#define IDC_STATIC_DOC                  1214
#define IDC_CHECK_RIGHT_CLICK_SCROLLING 1215
#define IDC_OBJECT_TYPE                 1216
#define IDC_STATIC_DELAY                1216
#define IDC_OBJECTDESCRIPTION           1217
#define IDC_STATIC_POLL_FREQUENCY       1217
#define IDC_OBJECTSCREENNAME            1218
#define IDC_COMBO_AZIMUTH               1218
#define IDC_OBJECTBLOCKNAME             1219
#define IDC_COMBO_ORBIT                 1219
#define IDC_SELECT_ALL                  1220
#define IDC_CHECK_STARTING_POS          1220
#define IDC_REPLACE                     1221
#define IDC_MEMBERLIST                  1221
#define IDC_CHECK_OVERRIDE_DETECT       1221
#define IDC_REMOVEMEMBER                1222
#define IDC_BUTTON_DELETE_ASPECT_OVERRIDE 1222
#define IDC_COMBO_EXISTING_HOTPOINT     1223
#define IDC_MAP_NAME                    1228
#define IDC_RADIO_SELECT                1238
#define IDC_RADIO_LINK                  1239
#define IDC_RADIO_MOVE                  1240
#define IDC_RADIO_PATROL                1241
#define IDC_TRIGGER_TREE                1242
#define IDC_RADIO_STOP                  1242
#define IDC_RADIO_FOLLOW                1243
#define IDC_RADIO_GUARD                 1244
#define IDC_RADIO_ATTACK                1245
#define IDC_RADIO_GET                   1246
#define IDC_RADIO_DROP                  1247
#define IDC_NEW_TRIGGER                 1248
#define IDC_RADIO_USE                   1248
#define IDC_EDIT_TRIGGER                1249
#define IDC_RADIO_EQUIP                 1249
#define IDC_COPY_TRIGGER                1250
#define IDC_RADIO_GIVE                  1250
#define IDC_REMOVE_TRIGGER              1251
#define IDC_BUTTON_SELECT_TEXTURE       1253
#define IDC_STATIC_TEXTURE              1254
#define IDC_CHECK_HEX                   1255
#define IDC_CHECK_LOAD_DECALS           1257
#define IDC_COMBO_TEMPLATE              1258
#define IDC_COMBO_Y                     1260
#define IDC_COMBO_Z                     1261
#define IDC_ACTION_COMBO                1262
#define IDC_COMBO_X                     1262
#define IDC_EDIT_NEAR_PLANE             1263
#define IDC_EDIT_FAR_PLANE              1264
#define IDC_STATIC_NODE                 1265
#define IDC_CONDITION_COMBO             1266
#define IDC_BUTTON_TERRAIN_COLOR        1266
#define IDC_BUTTON_DELETE_INVENTORY     1272
#define IDC_COMBO_ENVIRONMENTMAP        1273
#define IDC_CHECK_PLACE_POINTS          1274
#define IDC_COMBO_PATHS                 1276
#define IDC_PARTY_NODE_CURRENT_MEMBER   1277
#define IDC_BUTTON_NEW_PATH             1277
#define IDC_PARTY_NODE                  1278
#define IDC_BUTTON_REMOVE_PATH          1278
#define IDC_BUTTON_REPORTS              1279
#define IDC_DIRECTIONAL_LIGHT_LIST      1280
#define IDC_NEW_LIGHT                   1282
#define IDC_EDIT_LIGHT                  1283
#define IDC_CHECK_AUTOSIZE              1283
#define IDC_REMOVE_LIGHT                1284
#define IDC_NODE_GUID                   1285
#define IDC_BUTTON_COLOR                1285
#define IDC_DOOR_ID                     1286
#define IDC_CHECK_PATH_SUMMARY          1286
#define IDC_BUTTON_GENERATE_REPORTS     1287
#define IDC_CHECK_ALLITEM               1288
#define IDC_CHECK_ENEMY                 1289
#define IDC_CHECK_PATH_SUMMARY_POINT    1290
#define IDC_CHECK_CONTAINERITEM         1291
#define IDC_CHECK_PLACEDITEM            1292
#define IDC_CHECK_ENEMYITEM             1293
#define IDC_CHECK_ALLITEM_POINT         1294
#define IDC_CHECK_ENEMY_POINT           1295
#define IDC_CHECK_CONTAINERITEM_POINT   1296
#define IDC_STATIC_TYPE                 1297
#define IDC_CHECK_PLACEDITEM_POINT      1297
#define IDC_STATIC_NAME                 1298
#define IDC_CHECK_ENEMYITEM_POINT       1298
#define IDC_CHECK_PARTYMEMBER           1299
#define IDC_CHECK_PARTYMEMBER_POINT     1300
#define IDC_BUTTON_SEARCH_CMD           1300
#define IDC_BUTTON_AUTO_CLEAN           1301
#define IDC_BUTTON_UPDATE               1302
#define IDC_CHECK_REGION                1303
#define IDC_CHECK_TUNING_LOAD           1304
#define IDC_BUTTON_NEW_SCRIPT           1305
#define IDC_BUTTON_RUN_SCRIPT           1306
#define IDC_BUTTON_SAVE_SCRIPT          1307
#define IDC_BUTTON_LOAD_SCRIPT          1308
#define IDC_BUTTON_STOP_SCRIPTS         1309
#define IDC_STATIC_LINE1                1310
#define IDC_STATIC_SOURCE               1310
#define IDC_STATIC_DEST                 1311
#define IDC_STATIC_TESTING              1312
#define IDC_STATIC_DELETE               1314
#define IDC_STATIC_SCRIPT               1315
#define IDC_BUTTON_ADD_COMMAND          1316
#define IDC_BUTTON_REMOVE_COMMAND       1317
#define IDC_BUTTON_EDIT_PARAMETERS      1318
#define IDC_TREE_STITCH                 1319
#define IDC_CHECK_DRAW_COMMANDS         1319
#define IDC_BUTTON_REMOVE               1320
#define IDC_COMBO_SCRIPT                1320
#define IDC_LIST_MAPS                   1321
#define IDC_BUTTON_SELECT_PRIMARY       1321
#define IDC_BUTTON_REMOVE_CHAPTER       1321
#define IDC_BUTTON_BUILD                1322
#define IDC_BUTTON_SELECT_SECONDARY     1322
#define IDC_CHECK_NON_INTERACTIVE       1323
#define IDC_CHECK_SELECT_ALL            1325
#define IDC_CHECK_INTERACTIVE           1326
#define IDC_BUTTON_USE_CURRENT_POSITION 1327
#define IDC_CHECK_GIZMOS                1327
#define IDC_CHECK_DRAW_DOOR_NUM         1328
#define IDC_CHECK_NON_GIZMOS            1328
#define IDC_STATIC_EFFECT_NAME          1329
#define IDC_STATIC_REMOVE               1330
#define IDC_BUTTON_ADD_PARAMETER        1331
#define IDC_BUTTON_REMOVE_PARAMETER     1332
#define IDC_COMBO_AVAILABLE_FLAGS       1333
#define IDC_BUTTON_ADD_FLAG             1334
#define IDC_BUTTON_CLEAR_FLAGS          1335
#define IDC_BUTTON_REMOVE_FLAG          1336
#define IDC_CHECK_USE_SKINS             1337
#define IDC_BUTTON_SET_PORTRAIT_WINDOW  1338
#define ID_BUTTON_GENERATE_PORTRAIT     1339
#define IDC_CHECK_NODE_POSITION_OVERRIDE 1340
#define IDC_PARAMETER_TREE              1342
#define IDC_CHECK_FOURCC                1342
#define IDC_RADIO_X                     1343
#define IDC_RADIO_Y                     1344
#define IDC_RADIO_Z                     1345
#define IDC_BUTTON_ORBIT_RESET          1350
#define IDC_BUTTON_AZIMUTH_RESET        1351
#define IDC_STATIC_INCREMENT_TEXT       1351
#define IDC_X                           1352
#define IDC_Y                           1353
#define IDC_Z                           1354
#define IDC_BUTTON_PROPERTIES           1355
#define IDC_CHECK_LOCK_CUSTOM_VIEW      1356
#define IDC_CHECK_SINGLE_OBJECT         1357
#define IDC_BUTTON_ADD                  1358
#define IDC_BUTTON_REMAP_SCIDS          1359
#define IDC_BUTTON_ADD_CHAPTER          1359
#define IDC_TREE_REGIONS                1360
#define IDC_TREE_ITEMS                  1366
#define IDC_BUTTON_ADVANCED             1367
#define IDC_CHECK_OCCLUDE_CAMERA        1368
#define IDC_CHECK_BOUNDS_CAMERA         1369
#define IDC_BUTTON_DUPLICATE            1370
#define IDC_BUTTON_ELEV                 1371
#define IDC_TREE_MAPS                   1372
#define IDC_CHECK_LOAD_LIGHTS           1373
#define IDC_BUTTON_SELECT_ALL           1375
#define IDC_CHECK_MASTER_STATS          1377
#define IDC_BUTTON_DESELECT_MAP         1378
#define IDC_BUTTON_SELECT_MAP           1379
#define IDC_CHECK_VISIBLE               1382
#define IDC_BUTTON_RESET                1383
#define IDC_BUTTON_CLEAR                1384
#define IDC_TREE_GROUPS                 1385
#define IDC_BUTTON_SHOW                 1386
#define IDC_BUTTON_HIDE                 1387
#define IDC_CHECK_ROTATE_GROUP_MODE     1390
#define IDC_BUTTON_RANDOM_ROTATION      1391
#define IDC_BUTTON_ADD_SELECTION        1392
#define IDC_BUTTON_REMOVE_SELECTION     1393
#define IDC_BUTTON_SELECT_GROUP         1394
#define IDC_BUTTON_DESELECT_GROUP       1395
#define IDC_BUTTON_SHOW_SELECTION       1396
#define IDC_BUTTON_HIDE_SELECTION       1397
#define IDC_STATIC_OCCUPANTS            1398
#define IDC_BUTTON_PLACE_MACRO          1401
#define IDC_BUTTON_DEFINE_MACRO         1402
#define IDC_BUTTON_DELETE_MACRO         1403
#define IDC_CHECK_LOGICAL_FLAG          1404
#define IDC_CHECK_LOAD_LOGICAL_FLAGS    1406
#define IDC_CHECK_YAW                   1407
#define IDC_CHECK_PITCH                 1408
#define IDC_CHECK_ROLL                  1409
#define IDC_CHECK_RANDOM_SCALE          1410
#define IDC_BUTTON_DEFAULTS             1411
#define IDC_CHECK_FULL_RECALC           1412
#define IDC_BUTTON_SCALE                1416
#define IDC_CHECK_CAMERA_FADE           1417
#define IDC_BUTTON_COPY_TO_CLIPBOARD    1418
#define IDC_BUTTON_SET_CLEAR_COLOR      1419
#define IDC_CHECK_LOAD_LOGICAL          1421
#define IDC_COMBO_GROUPS                1422
#define IDC_BUTTON_HIDE_GROUP           1423
#define IDC_BUTTON_SHOW_GROUP           1424
#define IDC_BUTTON_ADD_TO_GROUP         1425
#define IDC_BUTTON_NEW_GROUP            1427
#define IDC_BUTTON_DELETE_GROUP         1428
#define IDC_CHECK_SECTION               1429
#define IDC_CHECK_LEVEL                 1430
#define IDC_CHECK_OBJECT                1431
#define IDC_COMBO_STARTING_GROUP        1437
#define IDC_BUTTON_EDIT                 1438
#define IDC_STATIC_GROUP_NAME           1439
#define IDC_CHECK_DEFAULT               1440
#define IDC_CHECK_CONVERT_NODE_INDEX    1441
#define IDC_CHECK_DEV_ONLY              1442
#define IDC_CHECK_LIGHT_HUD             1443
#define IDC_CHECK_SINGLEPLAYER          1444
#define IDC_CHECK_MULTIPLAYER           1445
#define IDC_BUTTON_EQUIPMENT_LIST       1446
#define IDC_CHECK_CAN_SELF_DESTRUCT     1448
#define IDC_CHECK_LIGHT_LOCKED          1450
#define IDC_BUTTON_NEW_MAP              1451
#define IDC_BUTTON_HELP                 1452
#define IDC_EDIT_WORLD_FRUSTUM_RADIUS   1453
#define IDC_EDIT_WORLD_INTEREST_RADIUS  1454
#define IDC_BUTTON_DEFAULT_REGION_ID    1456
#define IDC_EDIT_REGION_ID              1457
#define IDC_BUTTON_DEFAULT_SCID_RANGE   1458
#define IDC_BUTTON_DEFAULT_WORLD_FRUSTUM_RADIUS 1459
#define IDC_EDIT_MESH_RANGE             1459
#define IDC_BUTTON_DEFAULT_WORLD_INTEREST_RADIUS 1460
#define IDC_BUTTON_DEFAULT_MESH_RANGE   1460
#define IDC_BUTTON_DEFAULT_WORLD_FRUSTUM 1461
#define IDC_BUTTON_WORLD_INTEREST_RADIUS 1462
#define IDC_BUTTON_ADD_LEVEL            1464
#define IDC_BUTTON_REMOVE_LEVEL         1466
#define IDC_STATIC_CONVERSATION         1472
#define IDC_COMBO_AUDIO_SAMPLE          1473
#define IDC_CHECK_QUEST_DIALOGUE        1475
#define IDC_STATIC_TEMPLATE_NAME        1476
#define IDC_LIST_EXISTING_CONVERSATIONS 1477
#define IDC_BUTTON_NEW_LINE             1478
#define IDC_BUTTON_EDIT_LINE            1479
#define IDC_BUTTON_REMOVE_LINE          1480
#define IDC_BUTTON_NEW_GOODBYE          1481
#define IDC_EDIT_LINE                   1482
#define IDC_COMBO_BUTTON_CHOICE         1483
#define IDC_EDIT_ORDER                  1484
#define IDC_BUTTON_ACTIVATE_QUESTS      1485
#define IDC_BUTTON_COMPLETE_QUESTS      1486
#define IDC_LIST_QUESTS                 1487
#define IDC_COMBO_QUESTS                1488
#define IDC_EDIT_TEXT_1                 1489
#define IDC_EDIT_CONVERSATION           1490
#define IDC_COMBO_SAMPLES               1491
#define IDC_COMBO_ORDER                 1492
#define IDC_COMBO_EXISTING_CONVERSATIONS 1493
#define IDC_DEST_FILE_CHOICE            1495
#define IDC_BROWSE_DEST_FILE            1496
#define IDC_BROWSE_SOURCE_FOLDER        1497
#define IDC_PROGRESS                    1498
#define IDC_AUTHOR                      1498
#define IDC_LOG                         1499
#define IDC_DESCRIPTION                 1499
#define IDC_OUTPUT_PREFIX               1500
#define IDC_OVERWRITE_FILES             1500
#define IDC_COPYRIGHT                   1501
#define IDC_DEFAULT_DEST_FOLDER         1501
#define IDC_EXTRACT_LQD                 1502
#define IDC_REPROCESS_FILES             1503
#define IDC_PRIORITY                    1504
#define IDC_RECOMPILE_LQD               1505
#define IDC_INCLUDE_LQD                 1506
#define IDC_LQD_INCLUDE                 1506
#define IDC_VERIFY_TANK                 1507
#define IDC_USE_BACKUP                  1508
#define IDC_COMBO_AWARD_SKRIT           1509
#define IDC_COMBO_CHAPTER               1510
#define IDC_TITLE                       1511
#define IDC_LIST_QUEST_UPDATES          1511
#define IDC_PROTECTED_CONTENT           1512
#define IDC_COMPILE                     1513
#define IDC_BUTTON_ADD_QUEST            1514
#define IDC_BUTTON_EDIT_QUEST           1515
#define IDC_BUTTON_REMOVE_QUEST         1516
#define IDC_EDIT_QUEST                  1517
#define IDC_EDIT_CHAPTER                1518
#define IDC_EDIT_CHAPTER_IMAGE          1519
#define IDC_COMBO_SAMPLE                1520
#define IDC_EDIT_QUEST_IMAGE            1521
#define IDC_COMBO_VICTORY_SAMPLE        1522
#define IDC_COMBO_CONVERSATIONS         1523
#define IDC_LQD_COMPILE                 1524
#define IDC_SOURCE_FILE_CHOICE          1524
#define IDC_GENERATE_DUMP               1525
#define IDC_BROWSE_SOURCE_FILE          1525
#define IDC_MIN_VERSION                 1526
#define IDC_BROWSE_DEST_FOLDER          1526
#define IDC_CHECK_REQUIRED_UPDATE       1527
#define IDC_DEST_FOLDER_CHOICE          1527
#define IDC_LQD_DELETE                  1528
#define IDC_STATIC_SCALE                1528
#define IDC_DEV_ONLY                    1529
#define IDC_COMBO_STITCH_IDS            1529
#define IDC_NO_COMPRESSION              1530
#define IDC_BUTTON_ADD_STITCHES         1530
#define IDC_COMPRESS_FILES              1531
#define IDC_BUTTON_UNDO                 1531
#define IDC_COMBO_STITCH_REGION         1532
#define IDC_NO_REPROCESSING             1533
#define IDC_BUTTON_SELECT_ALL_TEMPLATE  1533
#define IDC_PROGRESS_TEXT               1534
#define IDC_CHECK_UPDATE_SIEGE_ENGINE   1534
#define IDC_BUTTON_EDIT_CHAPTER         1535
#define IDC_TREE_MATCHES                1535
#define IDC_BUTTON_MATCH                1537
#define IDC_BUTTON_ATTACH               1538
#define IDC_CHECK_CAMERA_GAME           1539
#define IDC_CHECK_DRAW_CAMERA_TARGET    1541
#define IDC_CHECK_INTERIOR_MOOD         1542
#define IDC_BUTTON_CHANGE_COLOR         1544
#define IDC_EDIT_FOG_DENSITY            1545
#define IDC_EDIT_FRUSTUM_WIDTH          1546
#define IDC_EDIT_FRUSTUM_HEIGHT         1547
#define IDC_CHECK_LIGHTNING             1551
#define IDC_CHECK_RAIN_ENABLE           1552
#define IDC_CHECK_ENABLE_SNOW           1553
#define IDC_COMBO_ROOM_TYPE             1553
#define IDC_CHECK_FOG_ENABLE            1554
#define IDC_CHECK_ENABLE_WIND           1554
#define IDC_CHECK_FRUSTUM_ENABLE        1555
#define IDC_CHECK_MUSIC_ENABLE          1556
#define IDC_BUTTON_EDIT_MUSIC           1557
#define IDC_BUTTON_EDIT_WEATHER         1558
#define IDC_BUTTON_EDIT_PROPERTIES      1559
#define IDC_BUTTON_EDIT_FOG             1560
#define IDC_EDIT_RAIN_DENSITY           1561
#define IDC_EDIT_SNOW_DENSITY           1562
#define IDC_EDIT_WIND_VELOCITY          1563
#define IDC_BUTTON_AMBIENT_FILES        1564
#define IDC_TREE_MOODS                  1565
#define IDC_BUTTON_ADD_FOLDER           1566
#define IDC_BUTTON_TEST                 1567
#define IDC_BUTTON_STOP                 1568
#define IDC_STATIC_COLOR                1569
#define IDC_TREE_MOODS_TANKED           1569
#define IDC_TREE_RESOURCES              1570
#define IDC_BUTTON_TEST_BATTLE          1571
#define IDC_BUTTON_TEST_AMBIENT         1572
#define IDC_BUTTON_TEST_STANDARD        1573
#define IDC_CHECK_REMAP_ALL_REGION_MESHES 1574
#define IDC_EDIT_ORIGIN_Z               1576
#define IDC_CHECK_ENABLE_GRID           1578
#define IDC_BUTTON_USE_SELECTED_NODE_CENTER 1579
#define IDC_BUTTON_USE_DEFAULT_CENTER   1580
#define IDC_STATIC_CONVERSION           1581
#define IDC_CHECK_LABELS_INTERVAL       1582
#define IDC_CHECK_METER_POINTS          1585
#define IDC_CHECK_DRAW_METER_POINTS     1586
#define IDC_CHECK_SHOW_POINT_DISTANCES  1587
#define IDC_CHECK_DRAW_DEST_ID          1588
#define IDC_CHECK_DRAW_DOOR_NUMBERS     1589
#define IDC_CHECK_DRAW_MESH_BOX         1590
#define IDC_CHECK_ALLOW_INVALID_DOOR_MATCH 1592
#define IDC_STATIC_VALID_COLOR          1593
#define IDC_STATIC_INVALID_COLOR        1594
#define IDC_STATIC_DESTINATION_DOOR_COLOR 1595
#define IDC_BUTTON_VALID_COLOR          1596
#define IDC_BUTTON_INVALID_COLOR        1597
#define IDC_BUTTON_DEFAULT_SNAP         1598
#define IDC_CHECK_ROTATE_ORIENT         1599
#define IDC_BUTTON_DEFAULT_SNAP_DELAY   1600
#define IDC_CHECK_DRAW_DOORS            1601
#define IDC_CHECK_DOOR_GUESS            1602
#define IDC_CHECK_REMAP_TO_MESH_RANGE   1603
#define IDC_CHECK_CONVERT_GLOBAL_MAP    1604
#define ID_FILE_NEWMAP                  32771
#define ID_EDIT_DELETE                  32772
#define ID_VIEW_TOOLBARS_OBJECTS        32774
#define ID_VIEW_TOOLBARS_LIGHTS         32775
#define ID_VIEW_TOOLBARS_TRIGGERS       32776
#define ID_VIEW_TOOLBARS_GENERATORS     32777
#define ID_VIEW_TOOLBARS_CAMERAS        32778
#define ID_VIEW_TOOLBARS_PARTIES        32779
#define ID_VIEW_TOOLBARS_WAYPOINTS      32780
#define ID_VIEW_OBJECTS                 32781
#define ID_VIEW_LIGHTS                  32782
#define ID_VIEW_TRIGGERS                32783
#define ID_VIEW_GENERATORS              32784
#define ID_VIEW_CAMERAS                 32785
#define ID_VIEW_PARTIES                 32786
#define ID_VIEW_WAYPOINTS               32787
#define ID_VIEW_MESHPREVIEWER           32788
#define ID_VIEW_PREFERENCES             32789
#define ID_NODE_PROPERTIES              32790
#define ID_NODE_CURRENTNODESET          32791
#define ID_NODE_SETASTARGETNODE         32792
#define ID_NODE_SELECTALLNODES          32793
#define ID_NODE_NODELIST                32794
#define ID_NODE_MESHLIST                32795
#define ID_NODE_AUTOCONNECTNODES        32796
#define ID_OBJECT_PROPERTIES            32797
#define ID_OBJECT_AUTOSNAPTOGROUND      32798
#define ID_OBJECT_PARTIES_PARTYCONSTRUCTOR 32799
#define ID_OBJECT_PARTIES_PARTYEDITOR   32800
#define ID_OBJECT_CONTENTSEARCH         32801
#define ID_LIGHTING_AMBIENCE            32802
#define ID_LIGHTING_EDITDIRECTIONALLIGHTS 32803
#define ID_LIGHTING_DRAWDIRECTIONALLIGHTS 32804
#define ID_LIGHTING_UPDATESELECTEDNODESLIGHTING 32805
#define ID_LIGHTING_CALCULATEALLLIGHTS  32806
#define ID_SCRIPTING_SKRITEDITOR        32807
#define ID_SCRIPTING_SKRITCONSOLE       32808
#define ID_SETTINGS_MAP                 32809
#define ID_SETTINGS_REGION              32810
#define ID_VALIDATION_REMOVEINVALIDOBJECTLINKSFROMMAP 32811
#define ID_VALIDATION_REMOVEALLINVALIDOBJECTLINKS 32812
#define ID_OBJECT_PRECISIONSETTINGS     32813
#define ID_VIEW_KEYBOARDSHORTCUTS       32814
#define ID_NODE_STITCHMANAGER           32815
#define ID_FILE_STITCHBUILDER           32816
#define ID_FILE_CREATEBACKUPSONSAVE     32817
#define ID_FILE_SAVE_ALL                32818
#define ID_NODE_PAINTSELECTNODES        32819
#define ID_ADDTOCUSTOMVIEW              32820
#define ID_REMOVESELECTED               32822
#define ID_LOADALLCUSTOMVIEWS           32823
#define ID_SAVECUSTOMVIEW               32824
#define ID_NEWFOLDER                    32825
#define ID_NODE_SELECTLASTADDED         32827
#define ID_OBJECT_PLACEMENTMODE         32835
#define ID_NODE_AUTOCONNECTSELECTEDNODES 32836
#define ID_OBJECT_INVENTORY             32837
#define ID_OBJECT_EQUIPMENT             32838
#define ID_LIGHTING_UPDATEALLNODELIGHTING 32839
#define ID_OBJECT_SPOTSNAPPER           32840
#define ID_SETTINGS_BOOKMARKS           32841
#define ID_OBJECT_VALIDATION            32843
#define ID_VIEW_TOOLBARS_NODE           32852
#define ID_VIEW_TOOLBARS_SEARCH         32853
#define ID_VIEW_TOOLBARS_VIEW           32881
#define ID_FILE_BATCHLNCGENERATION      32882
#define ID_SETTINGS_STARTINGPOSITIONS   32883
#define ID_CAMERA_RESET                 32884
#define ID_BUTTON32885                  32885
#define ID_CAMERA_TOPVIEW               32886
#define ID_CAMERA_SIDEVIEW              32887
#define ID_VIEW_TOOLBARS_CAMERA         32888
#define ID_OBJECT_BUILDGLOBALCONTENT    32889
#define ID_BUTTON32890                  32890
#define ID_OBJECT_TRIGGERS              32891
#define ID_NODE_SHOWALLNODES            32892
#define ID_OBJECT_TEMPLATEPROPERTIES    32894
#define ID_VIEW_MODE_OBJECTS            32896
#define ID_VIEW_MODE_LIGHTS             32897
#define ID_VIEW_MODE_TRIGGERS           32898
#define ID_VIEW_MODE_CAMERAS            32900
#define ID_VIEW_MODE_PARTIES            32901
#define ID_VIEW_MODE_WAYPOINTS          32902
#define ID_VIEW_MODE_GENERATORS         32906
#define ID_VIEW_TOOLBARS_MODE           32910
#define ID_OBJECT_SELECTIONMODE         32911
#define ID_SETTINGS_MAPHOTPOINTS        32914
#define ID_SETTINGS_EDITREGIONHOTPOINTS 32915
#define ID_VIEW_SHOW_HOTPOINTS          32916
#define ID_VIEW_MODE_HOTPOINTS          32917
#define ID_OBJECT_OBJECTLIST            32918
#define ID_OBJECT_SHOWALLOBJECTS        32920
#define ID_VIEW_DEBUGHUDS               32921
#define ID_OBJECT_MODE_SELECTIONLOCKMODE 32922
#define ID_OBJECT_MODE_PLACEMENTLOCKMODE 32923
#define ID_NODE_HIDE                    32924
#define ID_VIEW_MODE_GIZMOS             32929
#define ID_VIEW_GIZMOS                  32931
#define ID_VIEW_MODE_NODE               32932
#define ID_VIEW_MODE_DECALS             32933
#define ID_SETTINGS_MAPHOTPOINTMANAGER  32937
#define ID_OBJECT_SEQUENCEEDITOR        32939
#define ID_VIEW_DECALPREFERENCES        32940
#define ID_OBJECT_ROTATE_MODE           32941
#define ID_VIEW_CAMERACONTROLLER        32943
#define ID_OBJECT_TUNINGPATHS           32944
#define ID_SCRIPTING_SIEGEFXEDITOR      32945
#define ID_VIEW_SELECTIONFILTERS        32946
#define ID_VIEW_MODE_LOGICALNODES       32947
#define ID_NODE_LOGICALNODEPROPERTIES   32948
#define ID_PREVIEWER_CAMERACONTROLLER   32949
#define ID_PREVIEWER                    32950
#define ID_OPTIONS_SHOWPORTRAITBOX      32951
#define ID_OPTIONS_IMPORTSELECTEDGAMEOBJECT 32952
#define ID_OBJECT_PORTRAITS             32953
#define ID_OBJECT_MOVEMENTLOCK          32957
#define ID_OBJECT_HIDECOMPONENTS        32958
#define ID_FILE_SCIDREMAPPER            32959
#define ID_TUNING_BATCHPATHDATAGENERATION 32960
#define ID_VIEW_MODE_TUNINGPOINTS       32962
#define ID_VIEW_TUNINGPOINTS            32963
#define ID_BUTTON32964                  32964
#define ID_NODE_RECALCULATEDECALS       32965
#define ID_OBJECT_GROUPING              32966
#define ID_OBJECT_MACROS                32967
#define ID_OBJECT_NEXTOBJECT            32968
#define ID_NODE_NODEFADEGROUPS          32969
#define ID_SETTINGS_STARTINGGROUPS      32970
#define ID_BUTTON_MOVEMENT_LOCK         32975
#define ID_BUTTON_PLACEMENT_LOCK_Y      32976
#define ID_BUTTON_MOVEMENT_LOCK_Z       32977
#define ID_BUTTON_NEXT_OBJECT           32978
#define ID_BUTTON_TRIGGER_PROPERTIES    32986
#define ID_DRAW_LOGICAL_NODES           32987
#define ID_DRAW_DOORS                   32988
#define ID_BUTTON_FADE_NODE_CAPS        32989
#define ID_BUTTON_MOVEMENT_LOCK_X       32990
#define ID_BUTTON_MOVEMENT_LOCK_Y       32991
#define ID_HIDE_NODE_CAPS               32992
#define ID_VIEW_TOOLBARS_PREFERENCES    32993
#define ID_TRIGGER_PROPERTIES           32994
#define ID_NEXT_OBJECT                  32995
#define ID_DRAW_DEBUGHUDS               32999
#define ID_TOOLS_CONVERSATIONEDITOR     33000
#define ID_TOOLS_GLOBALCONVERSATIONMANAGER 33001
#define ID_VIEW_RESETCAMERA             33002
#define ID_PREFERENCES_WIREFRAME        33003
#define ID_PREFERENCES_DONTLOADTEXTURES 33004
#define ID_VIEW_BACKGROUNDCOLOR         33005
#define ID_TOOLS_QUESTCHAPTEREDITOR     33006
#define ID_TOOLS_AUTOSTITCHTOOL         33007
#define ID_TOOLS_NODEMATCHER            33008
#define ID_TOOLS_MOODEDITOR             33009
#define ID_VIEW_GRIDSETTINGS            33010
#define ID_TOOLS_METERPOINTEDITOR       33012
#define ID_VIEW_MODE_NODEPLACEMENT      33013
#define ID_VIEW_VISUALNODEPLACEMENT     33015
#define IDS_STRING61204                 61204
#define IDS_STRING61205                 61205
#define IDS_STRING61206                 61206
#define IDS_STRING61207                 61207
#define IDS_STRING61208                 61208
#define IDS_STRING61209                 61209
#define IDS_STRING61210                 61210
#define IDS_STRING61211                 61211

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        435
#define _APS_NEXT_COMMAND_VALUE         33016
#define _APS_NEXT_CONTROL_VALUE         1605
#define _APS_NEXT_SYMED_VALUE           162
#endif
#endif
